export const BRAND_LOGOS: Record<string, string> = {
  honda: "/brands/honda.svg",
  yamaha: "/brands/yamaha.svg",
  suzuki: "/brands/suzuki.svg",
  tvs: "/brands/tvs.svg",
  cfmoto: "/brands/cfmoto.png",
  sym: "/brands/sym.png",
  kymco: "/brands/kymco.svg",
  hero: "/brands/hero.svg",
  "qj-motor": "/brands/qj.svg",
  zontes: "/brands/zontes.svg",
  kuba: "/brands/kuba.svg",
  rks: "/brands/rks.svg",
  mondial: "/brands/mondial.svg",
  yuki: "/brands/yuki.svg",
  arora: "/brands/arora.svg",
  benda: "/brands/benda.svg",
  peugeot: "/brands/peugeot.svg",
  "regal-raptor": "/brands/regal-raptor.svg",
  voge: "/brands/voge.svg",
  taro: "/brands/taro.svg",
  volta: "/brands/volta.svg",
};
