BRAND_DATA = [
    {"name": "Abush", "slug": "abush", "country": "Türkiye", "founded_year": None, "website": "", "description": ""},
    {"name": "Aprilia", "slug": "aprilia", "country": "İtalya", "founded_year": 1945, "website": "", "description": ""},
    {"name": "Arora", "slug": "arora", "country": "Türkiye", "founded_year": None, "website": "", "description": ""},
    {"name": "Asya Motor", "slug": "asya-motor", "country": "Türkiye", "founded_year": None, "website": "", "description": ""},
    {"name": "Bajaj", "slug": "bajaj", "country": "Hindistan", "founded_year": 1945, "website": "", "description": ""},
    {"name": "Belderia", "slug": "belderia", "country": "Türkiye", "founded_year": None, "website": "", "description": ""},
    {"name": "Benelli", "slug": "benelli", "country": "İtalya", "founded_year": None, "website": "", "description": ""},
    {"name": "Bianchi", "slug": "bianchi", "country": "İtalya", "founded_year": None, "website": "", "description": ""},
    {"name": "Bisan", "slug": "bisan", "country": "Türkiye", "founded_year": None, "website": "", "description": ""},
    {"name": "BMW", "slug": "bmw", "country": "Almanya", "founded_year": 1923, "website": "", "description": ""},
    {"name": "Brixton", "slug": "brixton", "country": "Avusturya", "founded_year": None, "website": "", "description": ""},
    {"name": "BSA", "slug": "bsa", "country": "İngiltere", "founded_year": None, "website": "", "description": ""},
    {"name": "Carraro", "slug": "carraro", "country": "Türkiye", "founded_year": None, "website": "", "description": ""},
    {"name": "CFMOTO", "slug": "cfmoto", "country": "Çin", "founded_year": 1989, "website": "", "description": ""},
    {"name": "CSN Motor", "slug": "csn-motor", "country": "", "founded_year": None, "website": "", "description": ""},
    {"name": "Çelik Motor", "slug": "celik-motor", "country": "Türkiye", "founded_year": None, "website": "", "description": ""},
    {"name": "Ducati", "slug": "ducati", "country": "İtalya", "founded_year": 1926, "website": "", "description": ""},
    {"name": "Falcon", "slug": "falcon", "country": "Türkiye", "founded_year": None, "website": "", "description": ""},
    {"name": "FYM", "slug": "fym", "country": "Çin", "founded_year": None, "website": "", "description": ""},
    {"name": "Haojin", "slug": "haojin", "country": "Çin", "founded_year": None, "website": "", "description": ""},
    {"name": "Haojue", "slug": "haojue", "country": "Çin", "founded_year": None, "website": "", "description": ""},
    {"name": "Harley-Davidson", "slug": "harley-davidson", "country": "ABD", "founded_year": 1903, "website": "", "description": ""},
    {"name": "Hero", "slug": "hero", "country": "Hindistan", "founded_year": None, "website": "", "description": ""},
    {"name": "Honda", "slug": "honda", "country": "Japonya", "founded_year": 1948, "website": "", "description": ""},
    {"name": "Hyundai", "slug": "hyundai", "country": "Güney Kore", "founded_year": None, "website": "", "description": ""},
    {"name": "Jawa", "slug": "jawa", "country": "Çekoslavakya", "founded_year": None, "website": "", "description": ""},
    {"name": "Kadırga", "slug": "kadirga", "country": "Türkiye", "founded_year": None, "website": "", "description": ""},
    {"name": "Kanuni", "slug": "kanuni", "country": "Türkiye", "founded_year": None, "website": "", "description": ""},
    {"name": "Kawasaki", "slug": "kawasaki", "country": "Japonya", "founded_year": 1896, "website": "", "description": ""},
    {"name": "Kral Motor", "slug": "kral-motor", "country": "Türkiye", "founded_year": None, "website": "", "description": ""},
    {"name": "KTM", "slug": "ktm", "country": "Avusturya", "founded_year": 1934, "website": "", "description": ""},
    {"name": "Kuba", "slug": "kuba", "country": "Türkiye", "founded_year": None, "website": "", "description": ""},
    {"name": "Kymco", "slug": "kymco", "country": "Tayvan", "founded_year": None, "website": "", "description": ""},
    {"name": "Lifan", "slug": "lifan", "country": "Çin", "founded_year": None, "website": "", "description": ""},
    {"name": "Lingken", "slug": "lingken", "country": "Çin", "founded_year": None, "website": "", "description": ""},
    {"name": "Mobylette", "slug": "mobylette", "country": "Fransa", "founded_year": None, "website": "", "description": ""},
    {"name": "Mondial", "slug": "mondial", "country": "Türkiye", "founded_year": None, "website": "", "description": ""},
    {"name": "Mosso", "slug": "mosso", "country": "Türkiye", "founded_year": None, "website": "", "description": ""},
    {"name": "Motolux", "slug": "motolux", "country": "", "founded_year": None, "website": "", "description": ""},
    {"name": "Motoran", "slug": "motoran", "country": "Türkiye", "founded_year": None, "website": "", "description": ""},
    {"name": "Motosan", "slug": "motosan", "country": "Türkiye", "founded_year": None, "website": "", "description": ""},
    {"name": "Motozeus", "slug": "motozeus", "country": "Türkiye", "founded_year": None, "website": "", "description": ""},
    {"name": "MZ", "slug": "mz", "country": "Almanya", "founded_year": None, "website": "", "description": ""},
    {"name": "Piaggio", "slug": "piaggio", "country": "İtalya", "founded_year": 1884, "website": "", "description": ""},
    {"name": "Puch", "slug": "puch", "country": "Avusturya", "founded_year": None, "website": "", "description": ""},
    {"name": "QJ Motor", "slug": "qj-motor", "country": "Çin", "founded_year": None, "website": "", "description": ""},
    {"name": "Ramzey", "slug": "ramzey", "country": "Türkiye", "founded_year": None, "website": "", "description": ""},
    {"name": "Regal Raptor", "slug": "regal-raptor", "country": "Çin", "founded_year": None, "website": "", "description": ""},
    {"name": "Revolt", "slug": "revolt", "country": "Türkiye", "founded_year": None, "website": "", "description": ""},
    {"name": "RKS", "slug": "rks", "country": "Türkiye", "founded_year": None, "website": "", "description": ""},
    {"name": "RMG Moto Gusto", "slug": "rmg-moto-gusto", "country": "", "founded_year": None, "website": "", "description": ""},
    {"name": "Salcano", "slug": "salcano", "country": "Türkiye", "founded_year": None, "website": "", "description": ""},
    {"name": "Seger", "slug": "seger", "country": "", "founded_year": None, "website": "", "description": ""},
    {"name": "Shinari", "slug": "shinari", "country": "Türkiye", "founded_year": None, "website": "", "description": ""},
    {"name": "Skygo", "slug": "skygo", "country": "Çin", "founded_year": None, "website": "", "description": ""},
    {"name": "Skyjet", "slug": "skyjet", "country": "Türkiye", "founded_year": None, "website": "", "description": ""},
    {"name": "Skyteam", "slug": "skyteam", "country": "Çin", "founded_year": None, "website": "", "description": ""},
    {"name": "Suzuki", "slug": "suzuki", "country": "Japonya", "founded_year": 1909, "website": "", "description": ""},
    {"name": "SYM", "slug": "sym", "country": "Tayvan", "founded_year": None, "website": "", "description": ""},
    {"name": "Taro", "slug": "taro", "country": "Türkiye", "founded_year": None, "website": "", "description": ""},
    {"name": "Texas", "slug": "texas", "country": "Türkiye", "founded_year": None, "website": "", "description": ""},
    {"name": "TGB", "slug": "tgb", "country": "Tayvan", "founded_year": None, "website": "", "description": ""},
    {"name": "Triumph", "slug": "triumph", "country": "İngiltere", "founded_year": 1902, "website": "", "description": ""},
    {"name": "Truva", "slug": "truva", "country": "Türkiye", "founded_year": None, "website": "", "description": ""},
    {"name": "TVS", "slug": "tvs", "country": "Hindistan", "founded_year": None, "website": "", "description": ""},
    {"name": "UğurSam", "slug": "ugursam", "country": "Türkiye", "founded_year": None, "website": "", "description": ""},
    {"name": "Ural", "slug": "ural", "country": "Rusya", "founded_year": None, "website": "", "description": ""},
    {"name": "Vespa", "slug": "vespa", "country": "İtalya", "founded_year": 1946, "website": "", "description": ""},
    {"name": "Vitello", "slug": "vitello", "country": "", "founded_year": None, "website": "", "description": ""},
    {"name": "Voge", "slug": "voge", "country": "Çin", "founded_year": None, "website": "", "description": ""},
    {"name": "Volta", "slug": "volta", "country": "Türkiye", "founded_year": None, "website": "", "description": ""},
    {"name": "Voskhod", "slug": "voskhod", "country": "Rusya", "founded_year": None, "website": "", "description": ""},
    {"name": "Yamaha", "slug": "yamaha", "country": "Japonya", "founded_year": 1955, "website": "", "description": ""},
    {"name": "Yuki", "slug": "yuki", "country": "Türkiye", "founded_year": None, "website": "", "description": ""},
    {"name": "Zealsun", "slug": "zealsun", "country": "Çin", "founded_year": None, "website": "", "description": ""},
    {"name": "Zelsun", "slug": "zelsun", "country": "Çin", "founded_year": None, "website": "", "description": ""},
     {"name": "Btwin", "slug": "btwin", "country": "Fransa", "founded_year": None, "website": "", "description": ""},
    {"name": "Dahon", "slug": "dahon", "country": "ABD", "founded_year": None, "website": "", "description": ""},
    {"name": "Kron", "slug": "kron", "country": "Türkiye", "founded_year": None, "website": "", "description": ""},
    {"name": "Foldo", "slug": "foldo", "country": "", "founded_year": None, "website": "", "description": ""},
    {"name": "Decathlon", "slug": "decathlon", "country": "Fransa", "founded_year": None, "website": "", "description": ""},
    {"name": "Brompton", "slug": "brompton", "country": "İngiltere", "founded_year": None, "website": "", "description": ""},
    {"name": "Corelli", "slug": "corelli", "country": "Türkiye", "founded_year": None, "website": "", "description": ""},
    {"name": "Tern", "slug": "tern", "country": "Tayvan", "founded_year": None, "website": "", "description": ""},
    {"name": "OLA", "slug": "ola", "country": "Hindistan", "founded_year": None, "website": "", "description": ""},
    {"name": "Peugeot", "slug": "peugeot", "country": "Fransa", "founded_year": None, "website": "", "description": ""},
    {"name": "Umut", "slug": "umut", "country": "Türkiye", "founded_year": None, "website": "", "description": ""},
    {"name": "Gazelle", "slug": "gazelle", "country": "Hollanda", "founded_year": None, "website": "", "description": ""},
]