TAG_DATA = [
    {"name": "İndirimli Ürünler", "slug": "indirimli-urunler", "description": ""},
    {"name": "Yeni Gelenler", "slug": "yeni-gelenler", "description": ""},
    {"name": "Bitmek Üzere Olanlar", "slug": "bitmek-uzere", "description": ""},
    {"name": "Outlet / Fırsat", "slug": "outlet-firsat", "description": ""},
    {"name": "Takas Fırsatı", "slug": "takas-firsati", "description": ""},
    {"name": "Öne Çıkanlar", "slug": "one-cikanlar", "description": ""},
    {"name": "B Ehliyeti ile Sürülebilenler", "slug": "b-ehliyeti-surulebilir", "description": ""},
    {"name": "A1 ile Sürülebilenler", "slug": "a1-surulebilir", "description": ""},
    {"name": "Yakında Gelecek Olanlar", "slug": "yakinda-gelecek", "description": ""},
    {"name": "2. El", "slug": "2-el", "description": ""},
    {"name": "Sıfır Faizli Taksit", "slug": "sifir-faizli-taksit", "description": ""},
    {"name": "Ücretsiz Kargo", "slug": "ucretsiz-kargo", "description": ""},
    {"name": "Şehir Merkezi Ücretsiz Kargo", "slug": "sehir-merkezi-ucretsiz-kargo", "description": ""},
    {"name": "Çok Satan", "slug": "cok-satan", "description": ""},
    {"name": "Sezon Sonu", "slug": "sezon-sonu", "description": ""},
    {"name": "Açık Kutu", "slug": "acik-kutu", "description": ""},
]