ECOMMERCE_ATTRIBUTE_OPTION_DATA = [
    # Renk (multi_select)
    {"attribute_slug": "renk", "value": "Siyah", "display_order": 10},
    {"attribute_slug": "renk", "value": "Beyaz", "display_order": 20},
    {"attribute_slug": "renk", "value": "Kırmızı", "display_order": 30},
    {"attribute_slug": "renk", "value": "Mavi", "display_order": 40},
    {"attribute_slug": "renk", "value": "Yeşil", "display_order": 50},
    {"attribute_slug": "renk", "value": "Sarı", "display_order": 60},
    {"attribute_slug": "renk", "value": "Turuncu", "display_order": 70},
    {"attribute_slug": "renk", "value": "Mor", "display_order": 80},
    {"attribute_slug": "renk", "value": "Gri", "display_order": 90},
    {"attribute_slug": "renk", "value": "Kahverengi", "display_order": 100},
    {"attribute_slug": "renk", "value": "Bej", "display_order": 110},
    {"attribute_slug": "renk", "value": "Krom", "display_order": 120},
    {"attribute_slug": "renk", "value": "Mat Siyah", "display_order": 130},
     {"attribute_slug": "renk", "value": "Krom", "display_order": 120},
    {"attribute_slug": "renk", "value": "Mat Siyah", "display_order": 130},
    {"attribute_slug": "renk", "value": "Lacivert", "display_order": 140},
    {"attribute_slug": "renk", "value": "Haki", "display_order": 150},
    {"attribute_slug": "renk", "value": "Turkuaz", "display_order": 160},
    {"attribute_slug": "renk", "value": "Kamuflaj", "display_order": 170},
    {"attribute_slug": "renk", "value": "Çift Renk", "display_order": 180},

    # Model Yılı (single_select, 2005-2027)
    {"attribute_slug": "model-yili", "value": "2005", "display_order": 10},
    {"attribute_slug": "model-yili", "value": "2006", "display_order": 20},
    {"attribute_slug": "model-yili", "value": "2007", "display_order": 30},
    {"attribute_slug": "model-yili", "value": "2008", "display_order": 40},
    {"attribute_slug": "model-yili", "value": "2009", "display_order": 50},
    {"attribute_slug": "model-yili", "value": "2010", "display_order": 60},
    {"attribute_slug": "model-yili", "value": "2011", "display_order": 70},
    {"attribute_slug": "model-yili", "value": "2012", "display_order": 80},
    {"attribute_slug": "model-yili", "value": "2013", "display_order": 90},
    {"attribute_slug": "model-yili", "value": "2014", "display_order": 100},
    {"attribute_slug": "model-yili", "value": "2015", "display_order": 110},
    {"attribute_slug": "model-yili", "value": "2016", "display_order": 120},
    {"attribute_slug": "model-yili", "value": "2017", "display_order": 130},
    {"attribute_slug": "model-yili", "value": "2018", "display_order": 140},
    {"attribute_slug": "model-yili", "value": "2019", "display_order": 150},
    {"attribute_slug": "model-yili", "value": "2020", "display_order": 160},
    {"attribute_slug": "model-yili", "value": "2021", "display_order": 170},
    {"attribute_slug": "model-yili", "value": "2022", "display_order": 180},
    {"attribute_slug": "model-yili", "value": "2023", "display_order": 190},
    {"attribute_slug": "model-yili", "value": "2024", "display_order": 200},
    {"attribute_slug": "model-yili", "value": "2025", "display_order": 210},
    {"attribute_slug": "model-yili", "value": "2026", "display_order": 220},
    {"attribute_slug": "model-yili", "value": "2027", "display_order": 230},
]