from .ecommerce import (
    COMMON_ATTRIBUTE_SLUGS,
    SEARCH_ATTRIBUTE_SLUGS,
)
from .electric import ELECTRIC_CORE_ATTRIBUTE_SLUGS


E_CAR_CATEGORY_SLUGS = [
    "e-car",
]


E_CAR_ATTRIBUTE_SLUGS = [
    *COMMON_ATTRIBUTE_SLUGS,
    *SEARCH_ATTRIBUTE_SLUGS,
    *ELECTRIC_CORE_ATTRIBUTE_SLUGS,
]
