from .ecommerce import (
    COMMON_ATTRIBUTE_SLUGS,
    SEARCH_ATTRIBUTE_SLUGS,
)
from .electric import ELECTRIC_CORE_ATTRIBUTE_SLUGS


E_MARKET_TIPI_CATEGORY_SLUGS = [
    "e-market-tipi",
]


E_MARKET_TIPI_ATTRIBUTE_SLUGS = [
    *COMMON_ATTRIBUTE_SLUGS,
    *SEARCH_ATTRIBUTE_SLUGS,
    *ELECTRIC_CORE_ATTRIBUTE_SLUGS,
]
