# Generated by Django 6.0.7 on 2026-07-31 16:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_brand'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttributeGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Özellik Grubu Adı')),
                ('slug', models.SlugField(max_length=120, unique=True, verbose_name='Slug')),
                ('description', models.TextField(blank=True, verbose_name='Açıklama')),
                ('display_order', models.PositiveIntegerField(default=0, verbose_name='Gösterim Sırası')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktif mi?')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncellenme Tarihi')),
            ],
            options={
                'verbose_name': 'Özellik Grubu',
                'verbose_name_plural': 'Özellik Grupları',
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Ürün Adı')),
                ('slug', models.SlugField(max_length=180, unique=True, verbose_name='Slug')),
                ('model_year', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Model Yılı')),
                ('engine_type', models.CharField(choices=[('gasoline', 'Benzinli'), ('electric', 'Elektrikli')], max_length=20, verbose_name='Motor Tipi')),
                ('short_description', models.CharField(blank=True, max_length=255, verbose_name='Kısa Açıklama')),
                ('description', models.TextField(blank=True, verbose_name='Ürün Açıklaması')),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='products/', verbose_name='Kapak Görseli')),
                ('is_featured', models.BooleanField(default=False, verbose_name='Öne Çıkan Ürün mü?')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktif mi?')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncellenme Tarihi')),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='catalog.brand', verbose_name='Marka')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='catalog.category', verbose_name='Kategori')),
            ],
            options={
                'verbose_name': 'Ürün',
                'verbose_name_plural': 'Ürünler',
                'ordering': ['brand__name', 'name'],
            },
        ),
    ]
