# Generated by Django 6.0.7 on 2026-07-31 16:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_attributegroup_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attribute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Özellik Adı')),
                ('slug', models.SlugField(max_length=140, unique=True, verbose_name='Slug')),
                ('data_type', models.CharField(choices=[('text', 'Metin'), ('integer', 'Tam Sayı'), ('decimal', 'Ondalıklı Sayı'), ('boolean', 'Evet / Hayır'), ('single_select', 'Tek Seçim'), ('multi_select', 'Çoklu Seçim')], default='text', max_length=20, verbose_name='Veri Tipi')),
                ('unit', models.CharField(blank=True, help_text='Örnek: cc, HP, Nm, kg, litre, km', max_length=30, verbose_name='Birim')),
                ('description', models.TextField(blank=True, verbose_name='Açıklama')),
                ('is_filterable', models.BooleanField(default=False, verbose_name='Filtrelenebilir mi?')),
                ('is_comparable', models.BooleanField(default=False, verbose_name='Karşılaştırmada Gösterilsin mi?')),
                ('is_searchable', models.BooleanField(default=False, verbose_name='Aranabilir mi?')),
                ('display_order', models.PositiveIntegerField(default=0, verbose_name='Gösterim Sırası')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktif mi?')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncellenme Tarihi')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='attributes', to='catalog.attributegroup', verbose_name='Özellik Grubu')),
            ],
            options={
                'verbose_name': 'Özellik',
                'verbose_name_plural': 'Özellikler',
                'ordering': ['group__display_order', 'display_order', 'name'],
                'constraints': [models.UniqueConstraint(fields=('group', 'name'), name='unique_attribute_name_per_group')],
            },
        ),
    ]
