# Generated by Django 6.0.7 on 2026-07-31 16:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_attribute'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryAttribute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_required', models.BooleanField(default=False, verbose_name='Zorunlu mu?')),
                ('is_filterable', models.BooleanField(default=False, verbose_name='Filtrede Gösterilsin mi?')),
                ('is_comparable', models.BooleanField(default=False, verbose_name='Karşılaştırmada Gösterilsin mi?')),
                ('display_order', models.PositiveIntegerField(default=0, verbose_name='Gösterim Sırası')),
                ('attribute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category_attributes', to='catalog.attribute', verbose_name='Özellik')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category_attributes', to='catalog.category', verbose_name='Kategori')),
            ],
            options={
                'verbose_name': 'Kategori Özelliği',
                'verbose_name_plural': 'Kategori Özellikleri',
                'ordering': ['category__name', 'display_order', 'attribute__name'],
                'constraints': [models.UniqueConstraint(fields=('category', 'attribute'), name='unique_attribute_per_category')],
            },
        ),
    ]
