# Generated by Django 6.0.7 on 2026-07-31 16:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_categoryattribute'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductAttributeValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.TextField(verbose_name='Değer')),
                ('attribute', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='product_values', to='catalog.attribute', verbose_name='Özellik')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attribute_values', to='catalog.product', verbose_name='Ürün')),
            ],
            options={
                'verbose_name': 'Ürün Özelliği',
                'verbose_name_plural': 'Ürün Özellikleri',
                'ordering': ['attribute__group__display_order', 'attribute__display_order'],
                'constraints': [models.UniqueConstraint(fields=('product', 'attribute'), name='unique_product_attribute')],
            },
        ),
    ]
