# Generated by Django 6.0.7 on 2026-07-31 17:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_productattributevalue'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='products/gallery/', verbose_name='Ürün Görseli')),
                ('alt_text', models.CharField(blank=True, help_text='SEO ve erişilebilirlik için görsel açıklaması.', max_length=180, verbose_name='Alternatif Metin')),
                ('is_primary', models.BooleanField(default=False, verbose_name='Ana Görsel mi?')),
                ('display_order', models.PositiveIntegerField(default=0, verbose_name='Gösterim Sırası')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='catalog.product', verbose_name='Ürün')),
            ],
            options={
                'verbose_name': 'Ürün Görseli',
                'verbose_name_plural': 'Ürün Görselleri',
                'ordering': ['display_order', 'id'],
            },
        ),
    ]
