# Generated by Django 6.0.7 on 2026-08-04 18:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_productimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='engine_type',
        ),
        migrations.RemoveField(
            model_name='product',
            name='model_year',
        ),
        migrations.AlterField(
            model_name='category',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='catalog.category', verbose_name='Üst Kategori'),
        ),
    ]
