# Generated by Django 6.0.7 on 2026-08-06 15:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0008_remove_product_engine_type_remove_product_model_year_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Ana Fiyat'),
        ),
        migrations.CreateModel(
            name='ProductVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(max_length=100, unique=True, verbose_name='Stok Kodu')),
                ('color', models.CharField(blank=True, max_length=100, verbose_name='Renk')),
                ('size', models.CharField(blank=True, max_length=50, verbose_name='Beden / Ölçü')),
                ('price', models.DecimalField(blank=True, decimal_places=2, help_text='Boş bırakılırsa ürünün ana fiyatı kullanılır.', max_digits=12, null=True, verbose_name='Varyant Fiyatı')),
                ('stock_quantity', models.PositiveIntegerField(default=0, verbose_name='Stok Adedi')),
                ('is_default', models.BooleanField(default=False, verbose_name='Varsayılan Varyant')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktif')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncellenme Tarihi')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='catalog.product', verbose_name='Ürün')),
            ],
            options={
                'verbose_name': 'Ürün Varyantı',
                'verbose_name_plural': 'Ürün Varyantları',
                'ordering': ('product', 'color', 'size'),
                'constraints': [models.UniqueConstraint(fields=('product', 'color', 'size'), name='unique_product_color_size')],
            },
        ),
    ]
