# Generated by Django 6.0.7 on 2026-08-06 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0009_product_price_productvariant'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ('brand__name', 'name'), 'verbose_name': 'Ürün', 'verbose_name_plural': 'Ürünler'},
        ),
        migrations.AddField(
            model_name='product',
            name='currency',
            field=models.CharField(choices=[('TRY', 'Türk Lirası'), ('USD', 'Amerikan Doları'), ('EUR', 'Euro')], default='TRY', max_length=3, verbose_name='Para Birimi'),
        ),
        migrations.AddField(
            model_name='product',
            name='product_code',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='Ürün Kodu'),
        ),
        migrations.AddField(
            model_name='product',
            name='stock_status',
            field=models.CharField(choices=[('in_stock', 'Stokta'), ('out_of_stock', 'Stokta Yok'), ('pre_order', 'Ön Sipariş'), ('on_request', 'Sipariş Üzerine')], default='in_stock', max_length=20, verbose_name='Stok Durumu'),
        ),
    ]
