# Generated by Django 6.0.7 on 2026-08-07 08:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0011_productvariant_barcode_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttributeOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=120, verbose_name='Seçenek')),
                ('display_order', models.PositiveIntegerField(default=0, verbose_name='Sıralama')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktif mi?')),
                ('attribute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='catalog.attribute', verbose_name='Özellik')),
            ],
            options={
                'verbose_name': 'Özellik Seçeneği',
                'verbose_name_plural': 'Özellik Seçenekleri',
                'ordering': ('attribute', 'display_order', 'value'),
                'constraints': [models.UniqueConstraint(fields=('attribute', 'value'), name='unique_attribute_option')],
            },
        ),
    ]
