# Generated by Django 6.1 on 2026-08-20 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0013_product_discount_price'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='productattributevalue',
            name='unique_product_attribute',
        ),
        migrations.AddConstraint(
            model_name='productattributevalue',
            constraint=models.UniqueConstraint(fields=('product', 'attribute', 'value'), name='unique_product_attribute_value'),
        ),
    ]
