# Generated by Django 6.1 on 2026-08-27 08:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0014_alter_productattributevalue_unique_constraint'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='instagram_url',
            field=models.URLField(blank=True, max_length=255, null=True, verbose_name='Instagram Bağlantısı'),
        ),
        migrations.AddField(
            model_name='product',
            name='whatsapp_number',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='WhatsApp Numarası'),
        ),
        migrations.CreateModel(
            name='ProductReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveSmallIntegerField(verbose_name='Puan')),
                ('comment', models.TextField(verbose_name='Yorum')),
                ('is_approved', models.BooleanField(default=False, verbose_name='Onaylandı mı?')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='catalog.product', verbose_name='Ürün')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_reviews', to=settings.AUTH_USER_MODEL, verbose_name='Kullanıcı')),
            ],
            options={
                'verbose_name': 'Ürün Yorumu',
                'verbose_name_plural': 'Ürün Yorumları',
                'ordering': ('-created_at',),
                'unique_together': {('product', 'user')},
            },
        ),
    ]
