# Generated by Django 6.1 on 2026-08-29 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0015_product_instagram_url_product_whatsapp_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoryattribute',
            name='is_highlight',
            field=models.BooleanField(default=False, verbose_name='Öne Çıkan Özellik mi?'),
        ),
    ]
