# Generated by Django 6.1 on 2026-08-29 18:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0016_categoryattribute_is_highlight'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductHighlightImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='products/highlights/', verbose_name='Görsel')),
                ('attribute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='highlight_images', to='catalog.attribute', verbose_name='Özellik')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='highlight_images', to='catalog.product', verbose_name='Ürün')),
            ],
            options={
                'verbose_name': 'Öne Çıkan Özellik Görseli',
                'verbose_name_plural': 'Öne Çıkan Özellik Görselleri',
                'constraints': [models.UniqueConstraint(fields=('product', 'attribute'), name='unique_highlight_image_per_product_attribute')],
            },
        ),
    ]
