# Generated by Django 6.1 on 2026-08-31 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0017_producthighlightimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='producthighlightimage',
            name='description',
            field=models.TextField(blank=True, help_text="1-3 cümlelik editoryal metin (örn: 'Şehir içi kullanım için dengeli güç sunar.')", verbose_name='Kısa Açıklama'),
        ),
        migrations.AddField(
            model_name='producthighlightimage',
            name='title',
            field=models.CharField(blank=True, help_text="Boş bırakılırsa özellik adı (örn: 'Motor Hacmi') kullanılır.", max_length=100, verbose_name='Başlık'),
        ),
    ]
