# Generated by Django 6.1 on 2026-09-01 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0018_producthighlightimage_description_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productvariant',
            options={'ordering': ('product', 'color', 'size', 'trim', 'capacity', 'wheel_size', 'material', 'bundle'), 'verbose_name': 'Ürün Varyantı', 'verbose_name_plural': 'Ürün Varyantları'},
        ),
        migrations.RemoveConstraint(
            model_name='productvariant',
            name='unique_product_color_size',
        ),
        migrations.AddField(
            model_name='productvariant',
            name='bundle',
            field=models.CharField(blank=True, help_text='Örn: Kask Hediyeli Paket', max_length=150, verbose_name='Paket İçeriği'),
        ),
        migrations.AddField(
            model_name='productvariant',
            name='capacity',
            field=models.CharField(blank=True, help_text='Örn: 40Ah, 60Ah, 125cc', max_length=100, verbose_name='Kapasite / Hacim'),
        ),
        migrations.AddField(
            model_name='productvariant',
            name='material',
            field=models.CharField(blank=True, help_text='Örn: Deri, Kumaş/Mesh', max_length=100, verbose_name='Malzeme'),
        ),
        migrations.AddField(
            model_name='productvariant',
            name='trim',
            field=models.CharField(blank=True, help_text='Örn: STD, DLX, ABS', max_length=100, verbose_name='Donanım Paketi'),
        ),
        migrations.AddField(
            model_name='productvariant',
            name='wheel_size',
            field=models.CharField(blank=True, help_text='Örn: 26, 27.5, 29', max_length=50, verbose_name='Jant / Teker Boyu'),
        ),
        migrations.AddConstraint(
            model_name='productvariant',
            constraint=models.UniqueConstraint(fields=('product', 'color', 'size', 'trim', 'capacity', 'wheel_size', 'material', 'bundle'), name='unique_product_variant_combination'),
        ),
    ]
