# Generated by Django 6.1 on 2026-09-01 21:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0020_tag_product_tags'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomepageBand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text="Anasayfada görünecek başlık, örn: 'Kampanyalı Ürünler'", max_length=150, verbose_name='Bant Başlığı')),
                ('display_order', models.PositiveIntegerField(default=0, verbose_name='Gösterim Sırası')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktif mi?')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi')),
                ('tag', models.ForeignKey(help_text='Bu bant, bu etikete sahip ürünleri gösterir.', on_delete=django.db.models.deletion.CASCADE, related_name='homepage_bands', to='catalog.tag', verbose_name='Etiket')),
            ],
            options={
                'verbose_name': 'Anasayfa Bandı',
                'verbose_name_plural': 'Anasayfa Bantları',
                'ordering': ('display_order', 'title'),
            },
        ),
    ]
