# Generated by Django 6.1 on 2026-09-03 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0021_homepageband'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kargo_teslimat', models.TextField(blank=True, verbose_name='Kargo ve Teslimat')),
                ('iade_degisim', models.TextField(blank=True, verbose_name='İade ve Değişim')),
                ('garanti_bilgisi', models.TextField(blank=True, verbose_name='Garanti Bilgisi')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncellenme Tarihi')),
            ],
            options={
                'verbose_name': 'Site İçeriği',
                'verbose_name_plural': 'Site İçeriği',
            },
        ),
    ]
