# Generated by Django 6.1 on 2026-09-03 09:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0022_sitecontent'),
    ]

    operations = [
        migrations.CreateModel(
            name='InstallmentOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank_name', models.CharField(help_text='Örn: Garanti BBVA, Yapı Kredi, Akbank', max_length=100, verbose_name='Banka Adı')),
                ('installment_count', models.PositiveIntegerField(help_text='Örn: 1 (tek çekim), 2, 3, 6, 9, 12', verbose_name='Taksit Sayısı')),
                ('rate', models.DecimalField(decimal_places=2, default=0, help_text='Taksitsiz/tek çekim ise 0 girin.', max_digits=5, verbose_name='Vade Farkı (%)')),
                ('display_order', models.PositiveIntegerField(default=0, verbose_name='Gösterim Sırası')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktif mi?')),
                ('brand', models.ForeignKey(blank=True, help_text='Boş bırakılırsa markadan bağımsız kural olur.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='installment_options', to='catalog.brand', verbose_name='Marka')),
                ('category', models.ForeignKey(blank=True, help_text='Boş bırakılırsa kategoriden bağımsız kural olur.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='installment_options', to='catalog.category', verbose_name='Kategori')),
            ],
            options={
                'verbose_name': 'Taksit Seçeneği',
                'verbose_name_plural': 'Taksit Seçenekleri',
                'ordering': ('brand__name', 'category__name', 'bank_name', 'installment_count'),
                'constraints': [models.UniqueConstraint(fields=('brand', 'category', 'bank_name', 'installment_count'), name='unique_installment_scope')],
            },
        ),
    ]
