# Generated by Django 6.1 on 2026-09-03 09:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0023_installmentoption'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductResource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Örn: Kullanım Kılavuzu, Temizlik Talimatı', max_length=150, verbose_name='Başlık')),
                ('file', models.FileField(help_text='PDF, kullanım kılavuzu, garanti belgesi vb.', upload_to='products/resources/', verbose_name='Dosya')),
                ('display_order', models.PositiveIntegerField(default=0, verbose_name='Gösterim Sırası')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resources', to='catalog.product', verbose_name='Ürün')),
            ],
            options={
                'verbose_name': 'Ürün Kaynağı',
                'verbose_name_plural': 'Ürün Kaynakları',
                'ordering': ('product', 'display_order', 'title'),
            },
        ),
    ]
