# Generated by Django 6.1 on 2026-09-18 16:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0025_favorite'),
    ]

    operations = [
        migrations.CreateModel(
            name='VehicleModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Örn: Freccia 150, Blade-250', max_length=100, verbose_name='Model Adı')),
                ('slug', models.SlugField(max_length=140, verbose_name='Slug')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktif mi?')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncellenme Tarihi')),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vehicle_models', to='catalog.brand', verbose_name='Marka')),
            ],
            options={
                'verbose_name': 'Araç Modeli',
                'verbose_name_plural': 'Araç Modelleri',
                'ordering': ('brand__name', 'name'),
            },
        ),
        migrations.AddField(
            model_name='product',
            name='vehicle_model',
            field=models.ForeignKey(blank=True, help_text='Sadece Taşıtlar kategorisindeki ürünlerde doldurulur.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='products', to='catalog.vehiclemodel', verbose_name='Araç Modeli'),
        ),
        migrations.AddConstraint(
            model_name='vehiclemodel',
            constraint=models.UniqueConstraint(fields=('brand', 'slug'), name='unique_vehicle_model_per_brand'),
        ),
    ]
