# Generated by Django 6.1 on 2026-09-30 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='email_verification_code',
            field=models.CharField(blank=True, max_length=6, null=True, verbose_name='E-posta Doğrulama Kodu'),
        ),
        migrations.AddField(
            model_name='user',
            name='email_verification_code_expires_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Doğrulama Kodu Son Kullanma Tarihi'),
        ),
    ]
