# Generated by Django 6.1 on 2026-09-30 19:49

from django.db import migrations


def backfill_email_verified(apps, schema_editor):
    # Email doğrulama sistemi devreye girmeden önce kayıt olmuş
    # kullanıcılar aniden login dışı kalmasın diye zaten var olan
    # herkes doğrulanmış sayılır. Bundan sonraki yeni kayıtlar
    # RegisterSerializer.create() üzerinden email_verified=False
    # ile başlayacak.
    User = apps.get_model("accounts", "User")
    User.objects.filter(email_verified=False).update(email_verified=True)


def reverse_noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_email_verification_code_and_more'),
    ]

    operations = [
        migrations.RunPython(backfill_email_verified, reverse_noop),
    ]
