ACCESSORIES_ATTRIBUTE_DATA = [
    # AKSESUAR BİLGİLERİ
    {
        "name": "Aksesuar Tipi",
        "slug": "aksesuar-tipi",
        "group_slug": "aksesuar-bilgileri",
        "data_type": "text",
        "unit": "",
        "display_order": 7200,
        "is_filterable": True,
        "is_comparable": True,
        "is_searchable": True,
    },
    {
        "name": "Kapasite",
        "slug": "aksesuar-kapasitesi",
        "group_slug": "aksesuar-bilgileri",
        "data_type": "decimal",
        "unit": "L",
        "display_order": 7210,
        "is_filterable": True,
        "is_comparable": True,
        "is_searchable": False,
    },
    {
        "name": "Malzeme",
        "slug": "aksesuar-malzemesi",
        "group_slug": "aksesuar-bilgileri",
        "data_type": "text",
        "unit": "",
        "display_order": 7220,
        "is_filterable": True,
        "is_comparable": True,
        "is_searchable": False,
    },
    {
        "name": "Su Geçirmezlik",
        "slug": "aksesuar-su-gecirmezlik",
        "group_slug": "aksesuar-bilgileri",
        "data_type": "boolean",
        "unit": "",
        "display_order": 7230,
        "is_filterable": True,
        "is_comparable": True,
        "is_searchable": False,
    },

    # BAĞLANTI VE TEKNOLOJİ
    {
        "name": "Bluetooth Bağlantısı",
        "slug": "bluetooth-baglantisi",
        "group_slug": "baglanti-ve-teknoloji",
        "data_type": "boolean",
        "unit": "",
        "display_order": 7300,
        "is_filterable": True,
        "is_comparable": True,
        "is_searchable": False,
    },
    {
        "name": "Menzil",
        "slug": "aksesuar-menzil",
        "group_slug": "baglanti-ve-teknoloji",
        "data_type": "integer",
        "unit": "m",
        "display_order": 7310,
        "is_filterable": False,
        "is_comparable": True,
        "is_searchable": False,
    },
    {
        "name": "Pil Ömrü",
        "slug": "aksesuar-pil-omru",
        "group_slug": "baglanti-ve-teknoloji",
        "data_type": "decimal",
        "unit": "saat",
        "display_order": 7320,
        "is_filterable": False,
        "is_comparable": True,
        "is_searchable": False,
    },
    {
        "name": "Video Çözünürlüğü",
        "slug": "video-cozunurlugu",
        "group_slug": "baglanti-ve-teknoloji",
        "data_type": "text",
        "unit": "",
        "display_order": 7330,
        "is_filterable": True,
        "is_comparable": True,
        "is_searchable": False,
    },
]