APPAREL_ATTRIBUTE_DATA = [
    # GENEL BİLGİLER
    {
        "name": "Ürün Türü",
        "slug": "urun-turu",
        "group_slug": "genel-bilgiler",
        "data_type": "text",
        "unit": "",
        "display_order": 2100,
        "is_filterable": True,
        "is_comparable": True,
        "is_searchable": True,
    },
    {
        "name": "Kullanım Türü",
        "slug": "kullanim-turu",
        "group_slug": "genel-bilgiler",
        "data_type": "text",
        "unit": "",
        "display_order": 2110,
        "is_filterable": True,
        "is_comparable": True,
        "is_searchable": True,
    },

    # MALZEME VE YAPI
    {
        "name": "Dış Malzeme",
        "slug": "dis-malzeme",
        "group_slug": "malzeme-ve-yapi",
        "data_type": "text",
        "unit": "",
        "display_order": 2200,
        "is_filterable": True,
        "is_comparable": True,
        "is_searchable": True,
    },
    {
        "name": "İç Astar Malzemesi",
        "slug": "ic-astar-malzemesi",
        "group_slug": "malzeme-ve-yapi",
        "data_type": "text",
        "unit": "",
        "display_order": 2210,
        "is_filterable": False,
        "is_comparable": True,
        "is_searchable": False,
    },
    {
        "name": "Aşınmaya Dayanıklı Bölge",
        "slug": "asinmaya-dayanikli-bolge",
        "group_slug": "malzeme-ve-yapi",
        "data_type": "boolean",
        "unit": "",
        "display_order": 2220,
        "is_filterable": True,
        "is_comparable": True,
        "is_searchable": False,
    },
    {
        "name": "Dikiş Yapısı",
        "slug": "dikis-yapisi",
        "group_slug": "malzeme-ve-yapi",
        "data_type": "text",
        "unit": "",
        "display_order": 2230,
        "is_filterable": False,
        "is_comparable": True,
        "is_searchable": False,
    },

    # KORUMA
    {
        "name": "Omuz Koruması",
        "slug": "omuz-korumasi",
        "group_slug": "koruma",
        "data_type": "boolean",
        "unit": "",
        "display_order": 2300,
        "is_filterable": True,
        "is_comparable": True,
        "is_searchable": False,
    },
    {
        "name": "Dirsek Koruması",
        "slug": "dirsek-korumasi",
        "group_slug": "koruma",
        "data_type": "boolean",
        "unit": "",
        "display_order": 2310,
        "is_filterable": True,
        "is_comparable": True,
        "is_searchable": False,
    },
    {
        "name": "Sırt Koruması",
        "slug": "sirt-korumasi",
        "group_slug": "koruma",
        "data_type": "boolean",
        "unit": "",
        "display_order": 2320,
        "is_filterable": True,
        "is_comparable": True,
        "is_searchable": False,
    },
    {
        "name": "Kalça Koruması",
        "slug": "kalca-korumasi",
        "group_slug": "koruma",
        "data_type": "boolean",
        "unit": "",
        "display_order": 2330,
        "is_filterable": True,
        "is_comparable": True,
        "is_searchable": False,
    },
    {
        "name": "Diz Koruması",
        "slug": "diz-korumasi",
        "group_slug": "koruma",
        "data_type": "boolean",
        "unit": "",
        "display_order": 2340,
        "is_filterable": True,
        "is_comparable": True,
        "is_searchable": False,
    },
    {
        "name": "Parmak Koruması",
        "slug": "parmak-korumasi",
        "group_slug": "koruma",
        "data_type": "boolean",
        "unit": "",
        "display_order": 2350,
        "is_filterable": True,
        "is_comparable": True,
        "is_searchable": False,
    },
    {
        "name": "Bilek Koruması",
        "slug": "bilek-korumasi",
        "group_slug": "koruma",
        "data_type": "boolean",
        "unit": "",
        "display_order": 2360,
        "is_filterable": True,
        "is_comparable": True,
        "is_searchable": False,
    },
    {
        "name": "Kaval Koruması",
        "slug": "kaval-korumasi",
        "group_slug": "koruma",
        "data_type": "boolean",
        "unit": "",
        "display_order": 2370,
        "is_filterable": True,
        "is_comparable": True,
        "is_searchable": False,
    },
    {
        "name": "Koruma Sertifika Seviyesi",
        "slug": "koruma-sertifika-seviyesi",
        "group_slug": "koruma",
        "data_type": "text",
        "unit": "",
        "display_order": 2380,
        "is_filterable": True,
        "is_comparable": True,
        "is_searchable": True,
    },

    # KONFOR
    {
        "name": "Çıkarılabilir İçlik",
        "slug": "cikarilabilir-iclik",
        "group_slug": "konfor",
        "data_type": "boolean",
        "unit": "",
        "display_order": 2400,
        "is_filterable": True,
        "is_comparable": True,
        "is_searchable": False,
    },
    {
        "name": "Ayarlanabilir Bel",
        "slug": "ayarlanabilir-bel",
        "group_slug": "konfor",
        "data_type": "boolean",
        "unit": "",
        "display_order": 2410,
        "is_filterable": True,
        "is_comparable": True,
        "is_searchable": False,
    },
    {
        "name": "Ayarlanabilir Kol",
        "slug": "ayarlanabilir-kol",
        "group_slug": "konfor",
        "data_type": "boolean",
        "unit": "",
        "display_order": 2420,
        "is_filterable": True,
        "is_comparable": True,
        "is_searchable": False,
    },
    {
        "name": "Esnek Paneller",
        "slug": "esnek-paneller",
        "group_slug": "konfor",
        "data_type": "boolean",
        "unit": "",
        "display_order": 2430,
        "is_filterable": True,
        "is_comparable": True,
        "is_searchable": False,
    },
    {
        "name": "Bağlantı Fermuarı",
        "slug": "baglanti-fermuari",
        "group_slug": "konfor",
        "data_type": "boolean",
        "unit": "",
        "display_order": 2440,
        "is_filterable": True,
        "is_comparable": True,
        "is_searchable": False,
    },
    {
        "name": "Dokunmatik Ekran Uyumu",
        "slug": "dokunmatik-ekran-uyumu",
        "group_slug": "konfor",
        "data_type": "boolean",
        "unit": "",
        "display_order": 2450,
        "is_filterable": True,
        "is_comparable": True,
        "is_searchable": False,
    },

    # HAVALANDIRMA
    {
        "name": "Havalandırma Fermuarı",
        "slug": "havalandirma-fermuari",
        "group_slug": "havalandirma",
        "data_type": "boolean",
        "unit": "",
        "display_order": 2500,
        "is_filterable": True,
        "is_comparable": True,
        "is_searchable": False,
    },
    {
        "name": "File Panel",
        "slug": "file-panel",
        "group_slug": "havalandirma",
        "data_type": "boolean",
        "unit": "",
        "display_order": 2510,
        "is_filterable": True,
        "is_comparable": True,
        "is_searchable": False,
    },

    # MEVSİM VE HAVA KOŞULLARI
    {
        "name": "Kullanım Mevsimi",
        "slug": "kullanim-mevsimi",
        "group_slug": "mevsim-ve-hava-kosullari",
        "data_type": "text",
        "unit": "",
        "display_order": 2600,
        "is_filterable": True,
        "is_comparable": True,
        "is_searchable": True,
    },
    {
        "name": "Su Geçirmezlik",
        "slug": "su-gecirmezlik",
        "group_slug": "mevsim-ve-hava-kosullari",
        "data_type": "boolean",
        "unit": "",
        "display_order": 2610,
        "is_filterable": True,
        "is_comparable": True,
        "is_searchable": False,
    },
    {
        "name": "Rüzgar Geçirmezlik",
        "slug": "ruzgar-gecirmezlik",
        "group_slug": "mevsim-ve-hava-kosullari",
        "data_type": "boolean",
        "unit": "",
        "display_order": 2620,
        "is_filterable": True,
        "is_comparable": True,
        "is_searchable": False,
    },
    {
        "name": "Termal İçlik",
        "slug": "termal-iclik",
        "group_slug": "mevsim-ve-hava-kosullari",
        "data_type": "boolean",
        "unit": "",
        "display_order": 2630,
        "is_filterable": True,
        "is_comparable": True,
        "is_searchable": False,
    },
    {
        "name": "Nefes Alabilirlik",
        "slug": "nefes-alabilirlik",
        "group_slug": "mevsim-ve-hava-kosullari",
        "data_type": "boolean",
        "unit": "",
        "display_order": 2640,
        "is_filterable": True,
        "is_comparable": True,
        "is_searchable": False,
    },

    # GÜVENLİK
    {
        "name": "Giyim Reflektif Detay",
        "slug": "giyim-reflektif-detay",
        "group_slug": "guvenlik",
        "data_type": "boolean",
        "unit": "",
        "display_order": 2700,
        "is_filterable": True,
        "is_comparable": True,
        "is_searchable": False,
    },

    # STANDARTLAR VE SERTİFİKALAR
    {
        "name": "CE Sertifikası",
        "slug": "ce-sertifikasi",
        "group_slug": "standartlar-ve-sertifikalar",
        "data_type": "text",
        "unit": "",
        "display_order": 2800,
        "is_filterable": True,
        "is_comparable": True,
        "is_searchable": True,
    },
]