APPAREL_RAIN_ATTRIBUTE_DATA = [
    {
        "name": "Yağmurluk Tipi",
        "slug": "yagmurluk-tipi",
        "group_slug": "genel-bilgiler",
        "data_type": "single_select",
        "unit": "",
        "display_order": 3400,
        "is_filterable": True,
        "is_comparable": True,
        "is_searchable": False,
    },
    {
        "name": "Paketlenebilir",
        "slug": "paketlenebilir",
        "group_slug": "kullanim-ve-konfor",
        "data_type": "boolean",
        "unit": "",
        "display_order": 3410,
        "is_filterable": True,
        "is_comparable": True,
        "is_searchable": False,
    },
    {
        "name": "Dikişler Bantlı",
        "slug": "dikis-bantli",
        "group_slug": "mevsim-ve-hava-kosullari",
        "data_type": "boolean",
        "unit": "",
        "display_order": 3420,
        "is_filterable": True,
        "is_comparable": True,
        "is_searchable": False,
    },
    {
        "name": "Isıya Dayanıklı Bacak Paneli",
        "slug": "isi-korumali-panel",
        "group_slug": "koruma-ve-guvenlik",
        "data_type": "boolean",
        "unit": "",
        "display_order": 3430,
        "is_filterable": True,
        "is_comparable": True,
        "is_searchable": False,
    },
]
