APPAREL_PANTS_ATTRIBUTE_DATA = [
    {
        "name": "Pantolon Tipi",
        "slug": "pantolon-tipi",
        "group_slug": "genel-bilgiler",
        "data_type": "single_select",
        "unit": "",
        "display_order": 3100,
        "is_filterable": True,
        "is_comparable": True,
        "is_searchable": False,
    },
    {
        "name": "Kalça Koruma",
        "slug": "kalca-koruma",
        "group_slug": "koruma-ve-guvenlik",
        "data_type": "single_select",
        "unit": "",
        "display_order": 3110,
        "is_filterable": True,
        "is_comparable": True,
        "is_searchable": False,
    },
    {
        "name": "Paça Boyu",
        "slug": "paca-boyu",
        "group_slug": "genel-bilgiler",
        "data_type": "single_select",
        "unit": "",
        "display_order": 3120,
        "is_filterable": True,
        "is_comparable": True,
        "is_searchable": False,
    },
]
