APPAREL_BOOTS_ATTRIBUTE_DATA = [
    {
        "name": "Konç Yüksekliği",
        "slug": "konc-yuksekligi",
        "group_slug": "genel-bilgiler",
        "data_type": "single_select",
        "unit": "",
        "display_order": 3300,
        "is_filterable": True,
        "is_comparable": True,
        "is_searchable": False,
    },
    {
        "name": "EN 13634 Sertifikası",
        "slug": "en-13634",
        "group_slug": "koruma-ve-guvenlik",
        "data_type": "boolean",
        "unit": "",
        "display_order": 3310,
        "is_filterable": True,
        "is_comparable": True,
        "is_searchable": False,
    },
    {
        "name": "Kapanma Tipi",
        "slug": "kapanma-tipi",
        "group_slug": "malzeme-ve-yapi",
        "data_type": "single_select",
        "unit": "",
        "display_order": 3320,
        "is_filterable": True,
        "is_comparable": True,
        "is_searchable": False,
    },
    {
        "name": "Taban Tipi",
        "slug": "taban-tipi",
        "group_slug": "malzeme-ve-yapi",
        "data_type": "single_select",
        "unit": "",
        "display_order": 3330,
        "is_filterable": True,
        "is_comparable": True,
        "is_searchable": False,
    },
    {
        "name": "Vites Pedi",
        "slug": "vites-pedi",
        "group_slug": "koruma-ve-guvenlik",
        "data_type": "boolean",
        "unit": "",
        "display_order": 3340,
        "is_filterable": True,
        "is_comparable": True,
        "is_searchable": False,
    },
    {
        "name": "Ayak Bileği Koruması",
        "slug": "ayak-bilegi-korumasi",
        "group_slug": "koruma-ve-guvenlik",
        "data_type": "boolean",
        "unit": "",
        "display_order": 3350,
        "is_filterable": True,
        "is_comparable": True,
        "is_searchable": False,
    },
]
