APPAREL_GLOVES_ATTRIBUTE_DATA = [
    {
        "name": "Bilek Tipi",
        "slug": "bilek-tipi",
        "group_slug": "genel-bilgiler",
        "data_type": "single_select",
        "unit": "",
        "display_order": 3200,
        "is_filterable": True,
        "is_comparable": True,
        "is_searchable": False,
    },
    {
        "name": "EN 13594 Seviyesi",
        "slug": "en-13594-seviyesi",
        "group_slug": "koruma-ve-guvenlik",
        "data_type": "single_select",
        "unit": "",
        "display_order": 3210,
        "is_filterable": True,
        "is_comparable": True,
        "is_searchable": False,
    },
    {
        "name": "Parmak Eklem Koruması",
        "slug": "eklem-korumasi",
        "group_slug": "koruma-ve-guvenlik",
        "data_type": "boolean",
        "unit": "",
        "display_order": 3220,
        "is_filterable": True,
        "is_comparable": True,
        "is_searchable": False,
    },
    {
        "name": "Avuç İçi Malzemesi",
        "slug": "avuc-ici-malzemesi",
        "group_slug": "malzeme-ve-yapi",
        "data_type": "single_select",
        "unit": "",
        "display_order": 3230,
        "is_filterable": True,
        "is_comparable": True,
        "is_searchable": False,
    },
    {
        "name": "Avuç İçi Slider",
        "slug": "avuc-ici-slider",
        "group_slug": "koruma-ve-guvenlik",
        "data_type": "boolean",
        "unit": "",
        "display_order": 3240,
        "is_filterable": True,
        "is_comparable": True,
        "is_searchable": False,
    },
    {
        "name": "Dokunmatik Uyumlu",
        "slug": "dokunmatik-uyumlu",
        "group_slug": "kullanim-ve-konfor",
        "data_type": "boolean",
        "unit": "",
        "display_order": 3250,
        "is_filterable": True,
        "is_comparable": True,
        "is_searchable": False,
    },
    {
        "name": "Isıtmalı",
        "slug": "isitmali",
        "group_slug": "kullanim-ve-konfor",
        "data_type": "boolean",
        "unit": "",
        "display_order": 3260,
        "is_filterable": True,
        "is_comparable": True,
        "is_searchable": False,
    },
]
