APPAREL_JACKET_ATTRIBUTE_DATA = [
    {
        "name": "Ürün Tipi",
        "slug": "mont-tipi",
        "group_slug": "genel-bilgiler",
        "data_type": "single_select",
        "unit": "",
        "display_order": 3000,
        "is_filterable": True,
        "is_comparable": True,
        "is_searchable": False,
    },
    {
        "name": "Havalandırma Fermuarları",
        "slug": "havalandirma-fermuarlari",
        "group_slug": "kullanim-ve-konfor",
        "data_type": "boolean",
        "unit": "",
        "display_order": 3010,
        "is_filterable": True,
        "is_comparable": True,
        "is_searchable": False,
    },
    {
        "name": "Ayarlanabilir Bel/Kol",
        "slug": "ayarlanabilir-bel-kol",
        "group_slug": "kullanim-ve-konfor",
        "data_type": "boolean",
        "unit": "",
        "display_order": 3020,
        "is_filterable": True,
        "is_comparable": True,
        "is_searchable": False,
    },
    {
        "name": "Su Geçirmez İç Cep",
        "slug": "su-gecirmez-ic-cep",
        "group_slug": "kullanim-ve-konfor",
        "data_type": "boolean",
        "unit": "",
        "display_order": 3030,
        "is_filterable": True,
        "is_comparable": True,
        "is_searchable": False,
    },
]
