APPAREL_SUIT_ATTRIBUTE_DATA = [
    {
        "name": "Tulum Tipi",
        "slug": "tulum-tipi",
        "group_slug": "genel-bilgiler",
        "data_type": "single_select",
        "unit": "",
        "display_order": 3500,
        "is_filterable": True,
        "is_comparable": True,
        "is_searchable": False,
    },
    {
        "name": "Aerodinamik Kambur",
        "slug": "aerodinamik-kambur",
        "group_slug": "kullanim-ve-konfor",
        "data_type": "boolean",
        "unit": "",
        "display_order": 3510,
        "is_filterable": True,
        "is_comparable": True,
        "is_searchable": False,
    },
    {
        "name": "Streç Paneller",
        "slug": "strec-paneller",
        "group_slug": "kullanim-ve-konfor",
        "data_type": "boolean",
        "unit": "",
        "display_order": 3520,
        "is_filterable": True,
        "is_comparable": True,
        "is_searchable": False,
    },
]
