APPAREL_BASE_LAYER_ATTRIBUTE_DATA = [
    {
        "name": "İçlik Tipi",
        "slug": "iclik-tipi",
        "group_slug": "genel-bilgiler",
        "data_type": "single_select",
        "unit": "",
        "display_order": 3600,
        "is_filterable": True,
        "is_comparable": True,
        "is_searchable": False,
    },
    {
        "name": "İçlik Malzemesi",
        "slug": "iclik-malzemesi",
        "group_slug": "malzeme-ve-yapi",
        "data_type": "single_select",
        "unit": "",
        "display_order": 3610,
        "is_filterable": True,
        "is_comparable": True,
        "is_searchable": False,
    },
    {
        "name": "Dikişsiz",
        "slug": "dikissiz",
        "group_slug": "kullanim-ve-konfor",
        "data_type": "boolean",
        "unit": "",
        "display_order": 3620,
        "is_filterable": True,
        "is_comparable": True,
        "is_searchable": False,
    },
    {
        "name": "Antibakteriyel",
        "slug": "antibakteriyel",
        "group_slug": "kullanim-ve-konfor",
        "data_type": "boolean",
        "unit": "",
        "display_order": 3630,
        "is_filterable": True,
        "is_comparable": True,
        "is_searchable": False,
    },
]
