# Ekipman (apparel) kategorileri için ortak özellik havuzu.
# Bir alanın burada olması her kategoriye otomatik gelmesi demek
# değildir -- her category_attributes/apparel_*.py dosyası buradan
# hangi slug'ları seçtiğini kendi listesinde belirtir.
APPAREL_COMMON_ATTRIBUTE_DATA = [
    # GENEL BİLGİLER
    {
        "name": "Cinsiyet",
        "slug": "cinsiyet",
        "group_slug": "genel-bilgiler",
        "data_type": "single_select",
        "unit": "",
        "display_order": 2900,
        "is_filterable": True,
        "is_comparable": True,
        "is_searchable": False,
    },
    {
        "name": "Sürüş Tarzı",
        "slug": "surus-tarzi",
        "group_slug": "genel-bilgiler",
        "data_type": "single_select",
        "unit": "",
        "display_order": 2905,
        "is_filterable": True,
        "is_comparable": True,
        "is_searchable": False,
    },
    {
        "name": "Kalıp",
        "slug": "kalip",
        "group_slug": "genel-bilgiler",
        "data_type": "single_select",
        "unit": "",
        "display_order": 2920,
        "is_filterable": True,
        "is_comparable": True,
        "is_searchable": False,
    },

    # MALZEME VE YAPI
    {
        "name": "Ana Malzeme",
        "slug": "ana-malzeme",
        "group_slug": "malzeme-ve-yapi",
        "data_type": "single_select",
        "unit": "",
        "display_order": 2915,
        "is_filterable": True,
        "is_comparable": True,
        "is_searchable": False,
    },
    {
        "name": "Dış Kumaş Detayı",
        "slug": "dis-kumas-detayi",
        "group_slug": "malzeme-ve-yapi",
        "data_type": "text",
        "unit": "",
        "display_order": 2950,
        "is_filterable": False,
        "is_comparable": True,
        "is_searchable": True,
    },

    # HAVA KOŞULLARI
    {
        "name": "Sezon",
        "slug": "sezon",
        "group_slug": "mevsim-ve-hava-kosullari",
        "data_type": "single_select",
        "unit": "",
        "display_order": 2910,
        "is_filterable": True,
        "is_comparable": True,
        "is_searchable": False,
    },
    {
        "name": "Su Geçirmez Membran",
        "slug": "su-gecirmez-membran",
        "group_slug": "mevsim-ve-hava-kosullari",
        "data_type": "single_select",
        "unit": "",
        "display_order": 2925,
        "is_filterable": True,
        "is_comparable": True,
        "is_searchable": False,
    },
    {
        "name": "Membran Teknolojisi",
        "slug": "membran-teknolojisi",
        "group_slug": "mevsim-ve-hava-kosullari",
        "data_type": "text",
        "unit": "",
        "display_order": 2930,
        "is_filterable": False,
        "is_comparable": True,
        "is_searchable": True,
    },
    {
        "name": "Termal Astar",
        "slug": "termal-astar",
        "group_slug": "mevsim-ve-hava-kosullari",
        "data_type": "single_select",
        "unit": "",
        "display_order": 2935,
        "is_filterable": True,
        "is_comparable": True,
        "is_searchable": False,
    },
    {
        "name": "İşlev",
        "slug": "islev",
        "group_slug": "mevsim-ve-hava-kosullari",
        "data_type": "single_select",
        "unit": "",
        "display_order": 2990,
        "is_filterable": True,
        "is_comparable": True,
        "is_searchable": False,
    },

    # KORUMA VE GÜVENLİK
    {
        "name": "Reflektör",
        "slug": "reflektor",
        "group_slug": "koruma-ve-guvenlik",
        "data_type": "boolean",
        "unit": "",
        "display_order": 2940,
        "is_filterable": True,
        "is_comparable": True,
        "is_searchable": False,
    },
    {
        "name": "EN 17092 Sınıfı",
        "slug": "en-17092-sinifi",
        "group_slug": "koruma-ve-guvenlik",
        "data_type": "single_select",
        "unit": "",
        "display_order": 2945,
        "is_filterable": True,
        "is_comparable": True,
        "is_searchable": False,
    },
    {
        "name": "Omuz-Dirsek Koruma",
        "slug": "omuz-dirsek-koruma",
        "group_slug": "koruma-ve-guvenlik",
        "data_type": "single_select",
        "unit": "",
        "display_order": 2960,
        "is_filterable": True,
        "is_comparable": True,
        "is_searchable": False,
    },
    {
        "name": "Sırt Koruma",
        "slug": "sirt-koruma",
        "group_slug": "koruma-ve-guvenlik",
        "data_type": "single_select",
        "unit": "",
        "display_order": 2965,
        "is_filterable": True,
        "is_comparable": True,
        "is_searchable": False,
    },
    {
        "name": "Göğüs Koruma",
        "slug": "gogus-koruma",
        "group_slug": "koruma-ve-guvenlik",
        "data_type": "single_select",
        "unit": "",
        "display_order": 2970,
        "is_filterable": True,
        "is_comparable": True,
        "is_searchable": False,
    },
    {
        "name": "Airbag",
        "slug": "airbag",
        "group_slug": "koruma-ve-guvenlik",
        "data_type": "single_select",
        "unit": "",
        "display_order": 2975,
        "is_filterable": True,
        "is_comparable": True,
        "is_searchable": False,
    },
    {
        "name": "Diz Koruma",
        "slug": "diz-koruma",
        "group_slug": "koruma-ve-guvenlik",
        "data_type": "single_select",
        "unit": "",
        "display_order": 2980,
        "is_filterable": True,
        "is_comparable": True,
        "is_searchable": False,
    },
    {
        "name": "Diz Slider",
        "slug": "diz-slider",
        "group_slug": "koruma-ve-guvenlik",
        "data_type": "boolean",
        "unit": "",
        "display_order": 2985,
        "is_filterable": True,
        "is_comparable": True,
        "is_searchable": False,
    },

    # KULLANIM VE KONFOR
    {
        "name": "Bağlantı Fermuarı",
        "slug": "baglanti-fermuari",
        "group_slug": "kullanim-ve-konfor",
        "data_type": "single_select",
        "unit": "",
        "display_order": 2955,
        "is_filterable": True,
        "is_comparable": True,
        "is_searchable": False,
    },
]
