ATV_ATTRIBUTE_DATA = [
    # Şanzıman ve aktarma
    {
        "name": "Diferansiyel Kilidi",
        "slug": "diferansiyel-kilidi",
        "group_slug": "sanziman-ve-aktarma",
        "data_type": "boolean",
        "unit": "",
        "display_order": 340,
        "is_filterable": True,
        "is_comparable": True,
        "is_searchable": False,
    },

    # Jant ve lastik
    {
        "name": "Beadlock Jant",
        "slug": "beadlock-jant",
        "group_slug": "jant-ve-lastik",
        "data_type": "boolean",
        "unit": "",
        "display_order": 840,
        "is_filterable": True,
        "is_comparable": True,
        "is_searchable": False,
    },

    # Güvenlik
    {
        "name": "EBS",
        "slug": "ebs",
        "group_slug": "guvenlik",
        "data_type": "boolean",
        "unit": "",
        "display_order": 1020,
        "is_filterable": True,
        "is_comparable": True,
        "is_searchable": False,
    },

    # Elektrik ve elektronik
    {
        "name": "EPS (Elektrikli Direksiyon)",
        "slug": "eps",
        "group_slug": "elektrik-ve-elektronik",
        "data_type": "boolean",
        "unit": "",
        "display_order": 930,
        "is_filterable": True,
        "is_comparable": True,
        "is_searchable": False,
    },

    # Donanım
    {
        "name": "Vinç Kapasitesi",
        "slug": "vinc-kapasitesi",
        "group_slug": "donanim",
        "data_type": "integer",
        "unit": "kg",
        "display_order": 1200,
        "is_filterable": True,
        "is_comparable": True,
        "is_searchable": False,
    },
    {
        "name": "Ön Tampon",
        "slug": "on-tampon",
        "group_slug": "donanim",
        "data_type": "boolean",
        "unit": "",
        "display_order": 1210,
        "is_filterable": True,
        "is_comparable": True,
        "is_searchable": False,
    },
    {
        "name": "Çelik Raf (Ön/Arka)",
        "slug": "celik-raf",
        "group_slug": "donanim",
        "data_type": "boolean",
        "unit": "",
        "display_order": 1221,
        "is_filterable": True,
        "is_comparable": True,
        "is_searchable": False,
    },
    {
        "name": "Plastik Raf (Ön/Arka)",
        "slug": "plastik-raf",
        "group_slug": "donanim",
        "data_type": "boolean",
        "unit": "",
        "display_order": 1222,
        "is_filterable": True,
        "is_comparable": True,
        "is_searchable": False,
    },
    {
        "name": "Ön Raf Kapasitesi",
        "slug": "on-raf-kapasitesi",
        "group_slug": "donanim",
        "data_type": "integer",
        "unit": "kg",
        "display_order": 1240,
        "is_filterable": True,
        "is_comparable": True,
        "is_searchable": False,
    },
    {
        "name": "Arka Raf Kapasitesi",
        "slug": "arka-raf-kapasitesi",
        "group_slug": "donanim",
        "data_type": "integer",
        "unit": "kg",
        "display_order": 1250,
        "is_filterable": True,
        "is_comparable": True,
        "is_searchable": False,
    },
    {
        "name": "Çekici Apartları",
        "slug": "cekici-apartlari",
        "group_slug": "donanim",
        "data_type": "boolean",
        "unit": "",
        "display_order": 1260,
        "is_filterable": True,
        "is_comparable": True,
        "is_searchable": False,
    },
    {
        "name": "Çekme Gücü",
        "slug": "cekme-gucu",
        "group_slug": "donanim",
        "data_type": "integer",
        "unit": "kg",
        "display_order": 1270,
        "is_filterable": True,
        "is_comparable": True,
        "is_searchable": False,
    },
    {
        "name": "Gidon Koruması",
        "slug": "gidon-korumasi",
        "group_slug": "donanim",
        "data_type": "boolean",
        "unit": "",
        "display_order": 1230,
        "is_filterable": True,
        "is_comparable": True,
        "is_searchable": False,
    },

    # Malzeme ve yapı
    {
        "name": "Şasi Malzemesi",
        "slug": "sasi-malzemesi",
        "group_slug": "malzeme-ve-yapi",
        "data_type": "text",
        "unit": "",
        "display_order": 100,
        "is_filterable": False,
        "is_comparable": True,
        "is_searchable": False,
    },

    # Genel bilgiler
    {
        "name": "Araç Sınıfı",
        "slug": "arac-sinifi",
        "group_slug": "genel-bilgiler",
        "data_type": "single_select",
        "unit": "",
        "display_order": 50,
        "is_filterable": True,
        "is_comparable": True,
        "is_searchable": True,
    },
]
