BATTERY_ATTRIBUTE_DATA = [
    # GENEL BİLGİLER
    {
        "name": "Akü Tipi",
        "slug": "aku-tipi",
        "group_slug": "genel-bilgiler",
        "data_type": "text",
        "unit": "",
        "display_order": 3600,
        "is_filterable": True,
        "is_comparable": True,
        "is_searchable": True,
    },
    {
        "name": "Bakım Durumu",
        "slug": "bakim-durumu",
        "group_slug": "genel-bilgiler",
        "data_type": "text",
        "unit": "",
        "display_order": 3610,
        "is_filterable": True,
        "is_comparable": True,
        "is_searchable": True,
    },

    # AKÜ ELEKTRİK DEĞERLERİ
    {
        "name": "Voltaj",
        "slug": "aku-voltaj",
        "group_slug": "aku-elektrik-degerleri",
        "data_type": "integer",
        "unit": "V",
        "display_order": 3700,
        "is_filterable": True,
        "is_comparable": True,
        "is_searchable": False,
    },
    {
        "name": "Kapasite",
        "slug": "aku-kapasite",
        "group_slug": "aku-elektrik-degerleri",
        "data_type": "decimal",
        "unit": "Ah",
        "display_order": 3710,
        "is_filterable": True,
        "is_comparable": True,
        "is_searchable": False,
    },
    {
        "name": "Soğuk Marş Akımı",
        "slug": "soguk-mars-akimi",
        "group_slug": "aku-elektrik-degerleri",
        "data_type": "integer",
        "unit": "CCA",
        "display_order": 3720,
        "is_filterable": True,
        "is_comparable": True,
        "is_searchable": False,
    },
    {
        "name": "Enerji",
        "slug": "aku-enerji",
        "group_slug": "aku-elektrik-degerleri",
        "data_type": "integer",
        "unit": "Wh",
        "display_order": 3730,
        "is_filterable": False,
        "is_comparable": True,
        "is_searchable": False,
    },

    # AKÜ BOYUTLARI
    {
        "name": "Uzunluk",
        "slug": "aku-uzunluk",
        "group_slug": "aku-boyutlari",
        "data_type": "integer",
        "unit": "mm",
        "display_order": 3800,
        "is_filterable": False,
        "is_comparable": True,
        "is_searchable": False,
    },
    {
        "name": "Genişlik",
        "slug": "aku-genislik",
        "group_slug": "aku-boyutlari",
        "data_type": "integer",
        "unit": "mm",
        "display_order": 3810,
        "is_filterable": False,
        "is_comparable": True,
        "is_searchable": False,
    },
    {
        "name": "Yükseklik",
        "slug": "aku-yukseklik",
        "group_slug": "aku-boyutlari",
        "data_type": "integer",
        "unit": "mm",
        "display_order": 3820,
        "is_filterable": False,
        "is_comparable": True,
        "is_searchable": False,
    },
    {
        "name": "Ağırlık",
        "slug": "aku-agirligi",
        "group_slug": "aku-boyutlari",
        "data_type": "decimal",
        "unit": "kg",
        "display_order": 3830,
        "is_filterable": False,
        "is_comparable": True,
        "is_searchable": False,
    },

    # AKÜ TEKNOLOJİSİ
    {
        "name": "Teknoloji",
        "slug": "aku-teknolojisi",
        "group_slug": "aku-teknolojisi",
        "data_type": "text",
        "unit": "",
        "display_order": 3900,
        "is_filterable": True,
        "is_comparable": True,
        "is_searchable": True,
    },
    {
        "name": "Kutup Yerleşimi",
        "slug": "kutup-yerlesimi",
        "group_slug": "aku-teknolojisi",
        "data_type": "text",
        "unit": "",
        "display_order": 3910,
        "is_filterable": True,
        "is_comparable": True,
        "is_searchable": False,
    },
    {
        "name": "Havalandırma",
        "slug": "aku-havalandirma",
        "group_slug": "aku-teknolojisi",
        "data_type": "text",
        "unit": "",
        "display_order": 3920,
        "is_filterable": False,
        "is_comparable": True,
        "is_searchable": False,
    },

    # UYUMLULUK
    {
        "name": "Uyumlu Motosiklet",
        "slug": "uyumlu-motosiklet",
        "group_slug": "uyumluluk",
        "data_type": "text",
        "unit": "",
        "display_order": 4000,
        "is_filterable": True,
        "is_comparable": False,
        "is_searchable": True,
    },

    # STANDARTLAR
    {
        "name": "Akü Garanti Süresi",
        "slug": "aku-garanti-suresi",
        "group_slug": "standartlar-ve-sertifikalar",
        "data_type": "integer",
        "unit": "Ay",
        "display_order": 4100,
        "is_filterable": False,
        "is_comparable": True,
        "is_searchable": False,
    },
]