BICYCLE_COMMON_ATTRIBUTE_DATA = [
    {
        "name": "Çerçeve Geometrisi",
        "slug": "cerceve-geometrisi",
        "group_slug": "cerceve",
        "data_type": "text",
        "unit": "",
        "display_order": 4000,
        "is_filterable": False,
        "is_comparable": True,
        "is_searchable": False,
    },
    {
        "name": "Jant Malzemesi",
        "slug": "bisiklet-jant-malzemesi",
        "group_slug": "tekerlek-ve-lastik",
        "data_type": "single_select",
        "unit": "",
        "display_order": 4010,
        "is_filterable": True,
        "is_comparable": True,
        "is_searchable": False,
    },
    {
        "name": "Krank Seti",
        "slug": "krank-seti",
        "group_slug": "vites-sistemi",
        "data_type": "text",
        "unit": "",
        "display_order": 4020,
        "is_filterable": False,
        "is_comparable": True,
        "is_searchable": True,
    },
    {
        "name": "Vites Aktarıcı",
        "slug": "vites-aktarici",
        "group_slug": "vites-sistemi",
        "data_type": "text",
        "unit": "",
        "display_order": 4030,
        "is_filterable": False,
        "is_comparable": True,
        "is_searchable": True,
    },
    {
        "name": "Sele Malzemesi",
        "slug": "sele-malzemesi",
        "group_slug": "bisiklet-donanimi",
        "data_type": "single_select",
        "unit": "",
        "display_order": 4040,
        "is_filterable": True,
        "is_comparable": True,
        "is_searchable": False,
    },
]
