BICYCLE_ATTRIBUTE_DATA = [
    # ÇERÇEVE
    {
        "name": "Çerçeve Malzemesi",
        "slug": "cerceve-malzemesi",
        "group_slug": "cerceve",
        "data_type": "text",
        "unit": "",
        "display_order": 5000,
        "is_filterable": True,
        "is_comparable": True,
        "is_searchable": True,
    },
    {
        "name": "Çerçeve Bedeni",
        "slug": "cerceve-bedeni",
        "group_slug": "cerceve",
        "data_type": "text",
        "unit": "",
        "display_order": 5010,
        "is_filterable": True,
        "is_comparable": True,
        "is_searchable": False,
    },
    # Çerçeve Geometrisi -> attributes/bicycle_common.py'ye taşındı

    # TEKERLEK VE LASTİK
    {
        "name": "Jant Çapı",
        "slug": "bisiklet-jant-capi",
        "group_slug": "tekerlek-ve-lastik",
        "data_type": "text",
        "unit": "inç",
        "display_order": 5100,
        "is_filterable": True,
        "is_comparable": True,
        "is_searchable": True,
    },
    {
        "name": "Lastik Genişliği",
        "slug": "bisiklet-lastik-genisligi",
        "group_slug": "tekerlek-ve-lastik",
        "data_type": "text",
        "unit": "",
        "display_order": 5110,
        "is_filterable": True,
        "is_comparable": True,
        "is_searchable": False,
    },
    # Jant Malzemesi -> attributes/bicycle_common.py'ye taşındı

    # VİTES SİSTEMİ
    {
        "name": "Vites Sayısı",
        "slug": "bisiklet-vites-sayisi",
        "group_slug": "vites-sistemi",
        "data_type": "integer",
        "unit": "",
        "display_order": 5200,
        "is_filterable": True,
        "is_comparable": True,
        "is_searchable": False,
    },
    {
        "name": "Vites Grubu Markası",
        "slug": "vites-grubu-markasi",
        "group_slug": "vites-sistemi",
        "data_type": "text",
        "unit": "",
        "display_order": 5210,
        "is_filterable": True,
        "is_comparable": True,
        "is_searchable": True,
    },
    {
        "name": "Şanzıman Tipi",
        "slug": "bisiklet-sanziman-tipi",
        "group_slug": "vites-sistemi",
        "data_type": "text",
        "unit": "",
        "display_order": 5220,
        "is_filterable": True,
        "is_comparable": True,
        "is_searchable": False,
    },

    # BİSİKLET FREN SİSTEMİ
    {
        "name": "Fren Tipi",
        "slug": "bisiklet-fren-tipi",
        "group_slug": "bisiklet-fren-sistemi",
        "data_type": "text",
        "unit": "",
        "display_order": 5300,
        "is_filterable": True,
        "is_comparable": True,
        "is_searchable": True,
    },
    {
        "name": "Fren Mekanizması",
        "slug": "fren-mekanizmasi",
        "group_slug": "bisiklet-fren-sistemi",
        "data_type": "text",
        "unit": "",
        "display_order": 5310,
        "is_filterable": True,
        "is_comparable": True,
        "is_searchable": False,
    },

    # BİSİKLET SÜSPANSİYONU
    {
        "name": "Ön Süspansiyon",
        "slug": "bisiklet-on-suspansiyon",
        "group_slug": "bisiklet-suspansiyonu",
        "data_type": "text",
        "unit": "",
        "display_order": 5400,
        "is_filterable": True,
        "is_comparable": True,
        "is_searchable": False,
    },
    {
        "name": "Arka Süspansiyon",
        "slug": "bisiklet-arka-suspansiyon",
        "group_slug": "bisiklet-suspansiyonu",
        "data_type": "text",
        "unit": "",
        "display_order": 5410,
        "is_filterable": True,
        "is_comparable": True,
        "is_searchable": False,
    },
    {
        "name": "Süspansiyon Seyahati",
        "slug": "suspansiyon-seyahati",
        "group_slug": "bisiklet-suspansiyonu",
        "data_type": "integer",
        "unit": "mm",
        "display_order": 5420,
        "is_filterable": False,
        "is_comparable": True,
        "is_searchable": False,
    },

    # ELEKTRİKLİ SİSTEM kaldırıldı — e-bisiklet zaten elektrikli-* şemasını kullanıyor

    # BİSİKLET BOYUT VE AĞIRLIK
    {
        "name": "Ağırlık",
        "slug": "bisiklet-agirlik",
        "group_slug": "bisiklet-boyut-ve-agirlik",
        "data_type": "decimal",
        "unit": "kg",
        "display_order": 5600,
        "is_filterable": True,
        "is_comparable": True,
        "is_searchable": False,
    },
    {
        "name": "Maksimum Taşıma Kapasitesi",
        "slug": "bisiklet-tasima-kapasitesi",
        "group_slug": "bisiklet-boyut-ve-agirlik",
        "data_type": "decimal",
        "unit": "kg",
        "display_order": 5610,
        "is_filterable": False,
        "is_comparable": True,
        "is_searchable": False,
    },

    # BİSİKLET DONANIMI
    {
        "name": "Çamurluk",
        "slug": "camurluk",
        "group_slug": "bisiklet-donanimi",
        "data_type": "boolean",
        "unit": "",
        "display_order": 5700,
        "is_filterable": True,
        "is_comparable": True,
        "is_searchable": False,
    },
    {
        "name": "Bagaj",
        "slug": "bisiklet-bagaj",
        "group_slug": "bisiklet-donanimi",
        "data_type": "boolean",
        "unit": "",
        "display_order": 5710,
        "is_filterable": True,
        "is_comparable": True,
        "is_searchable": False,
    },
    {
        "name": "Işık",
        "slug": "bisiklet-isik",
        "group_slug": "bisiklet-donanimi",
        "data_type": "boolean",
        "unit": "",
        "display_order": 5720,
        "is_filterable": True,
        "is_comparable": True,
        "is_searchable": False,
    },
    {
        "name": "Standart (Kickstand)",
        "slug": "standart-kickstand",
        "group_slug": "bisiklet-donanimi",
        "data_type": "boolean",
        "unit": "",
        "display_order": 5730,
        "is_filterable": True,
        "is_comparable": True,
        "is_searchable": False,
    },
]