E_KASALI_ATTRIBUTE_DATA = [
    {
        "name": "Kabin",
        "slug": "kabin",
        "group_slug": "donanim",
        "data_type": "single_select",
        "unit": "",
        "display_order": 8100,
        "is_filterable": True,
        "is_comparable": True,
        "is_searchable": False,
    },
    {
        "name": "Direksiyon",
        "slug": "direksiyon",
        "group_slug": "donanim",
        "data_type": "single_select",
        "unit": "",
        "display_order": 8110,
        "is_filterable": True,
        "is_comparable": True,
        "is_searchable": False,
    },
    {
        "name": "Ön Panel",
        "slug": "on-panel",
        "group_slug": "donanim",
        "data_type": "single_select",
        "unit": "",
        "display_order": 8120,
        "is_filterable": True,
        "is_comparable": True,
        "is_searchable": False,
    },
]
