E_MARKET_TIPI_ATTRIBUTE_DATA = [
    {
        "name": "Arka Bagaj",
        "slug": "arka-bagaj-var-mi",
        "group_slug": "donanim",
        "data_type": "boolean",
        "unit": "",
        "display_order": 8000,
        "is_filterable": True,
        "is_comparable": True,
        "is_searchable": False,
    },
    {
        "name": "Yolcu Sayısı",
        "slug": "yolcu-sayisi",
        "group_slug": "boyutlar-ve-agirlik",
        "data_type": "single_select",
        "unit": "",
        "display_order": 8010,
        "is_filterable": True,
        "is_comparable": True,
        "is_searchable": False,
    },
    {
        "name": "Ayak Freni",
        "slug": "ayak-freni-var-mi",
        "group_slug": "fren-sistemi",
        "data_type": "boolean",
        "unit": "",
        "display_order": 8020,
        "is_filterable": True,
        "is_comparable": True,
        "is_searchable": False,
    },
]
