ECOMMERCE_ATTRIBUTE_DATA = [
    # Genel Bilgiler
    {
        "name": "Model Yılı",
        "slug": "model-yili",
        "group_slug": "genel-bilgiler",
        "data_type": "integer",
        "unit": "",
        "display_order": 10,
        "is_filterable": True,
        "is_comparable": True,
        "is_searchable": True,
    },

     {
        "name": "Renk",
        "slug": "renk",
        "group_slug": "genel-bilgiler",
        "data_type": "multi_select",
        "unit": "",
        "display_order": 15,
        "is_filterable": True,
        "is_comparable": True,
        "is_searchable": True,
    },
    
    {
        "name": "Menşei Ülke",
        "slug": "mensei-ulke",
        "group_slug": "genel-bilgiler",
        "data_type": "text",
        "unit": "",
        "display_order": 20,
        "is_filterable": True,
        "is_comparable": True,
        "is_searchable": True,
    },
    {
        "name": "Üretici",
        "slug": "uretici",
        "group_slug": "genel-bilgiler",
        "data_type": "text",
        "unit": "",
        "display_order": 30,
        "is_filterable": True,
        "is_comparable": True,
        "is_searchable": True,
    },

    # Uyumluluk
    {
        "name": "Uyumlu Marka",
        "slug": "uyumlu-marka",
        "group_slug": "uyumluluk",
        "data_type": "text",
        "unit": "",
        "display_order": 100,
        "is_filterable": True,
        "is_comparable": False,
        "is_searchable": True,
    },
    {
        "name": "Uyumlu Model",
        "slug": "uyumlu-model",
        "group_slug": "uyumluluk",
        "data_type": "text",
        "unit": "",
        "display_order": 110,
        "is_filterable": True,
        "is_comparable": False,
        "is_searchable": True,
    },
    {
        "name": "Uyumlu Yıllar",
        "slug": "uyumlu-yillar",
        "group_slug": "uyumluluk",
        "data_type": "text",
        "unit": "",
        "display_order": 120,
        "is_filterable": False,
        "is_comparable": False,
        "is_searchable": True,
    },

    # Standartlar
    {
        "name": "Garanti Süresi",
        "slug": "garanti-suresi",
        "group_slug": "standartlar-ve-sertifikalar",
        "data_type": "integer",
        "unit": "Ay",
        "display_order": 200,
        "is_filterable": False,
        "is_comparable": True,
        "is_searchable": False,
    },
    {
        "name": "Sertifikalar",
        "slug": "sertifikalar",
        "group_slug": "standartlar-ve-sertifikalar",
        "data_type": "text",
        "unit": "",
        "display_order": 210,
        "is_filterable": True,
        "is_comparable": True,
        "is_searchable": True,
    },

    # Bakım
    {
        "name": "Bakım Talimatı",
        "slug": "bakim-talimati",
        "group_slug": "bakim-ve-kullanim",
        "data_type": "text",
        "unit": "",
        "display_order": 300,
        "is_filterable": False,
        "is_comparable": False,
        "is_searchable": False,
    },
    {
        "name": "Kullanım Talimatı",
        "slug": "kullanim-talimati",
        "group_slug": "bakim-ve-kullanim",
        "data_type": "text",
        "unit": "",
        "display_order": 310,
        "is_filterable": False,
        "is_comparable": False,
        "is_searchable": False,
    },

    # Paket
    {
        "name": "Paket İçeriği",
        "slug": "paket-icerigi",
        "group_slug": "paket-icerigi",
        "data_type": "text",
        "unit": "",
        "display_order": 400,
        "is_filterable": False,
        "is_comparable": False,
        "is_searchable": False,
    },

    # -------------------------------------------------
# ARAMA / ÜRÜN KİMLİK BİLGİLERİ
# -------------------------------------------------

{
    "name": "OEM Kodu",
    "slug": "oem-kodu",
    "group_slug": "genel-bilgiler",
    "data_type": "text",
    "unit": "",
    "display_order": 500,
    "is_filterable": True,
    "is_comparable": False,
    "is_searchable": True,
},
{
    "name": "Üretici Parça Numarası (MPN)",
    "slug": "mpn",
    "group_slug": "genel-bilgiler",
    "data_type": "text",
    "unit": "",
    "display_order": 510,
    "is_filterable": False,
    "is_comparable": False,
    "is_searchable": True,
},
{
    "name": "EAN",
    "slug": "ean",
    "group_slug": "genel-bilgiler",
    "data_type": "text",
    "unit": "",
    "display_order": 520,
    "is_filterable": False,
    "is_comparable": False,
    "is_searchable": True,
},
{
    "name": "UPC",
    "slug": "upc",
    "group_slug": "genel-bilgiler",
    "data_type": "text",
    "unit": "",
    "display_order": 530,
    "is_filterable": False,
    "is_comparable": False,
    "is_searchable": True,
},
]