ELECTRIC_ATTRIBUTE_DATA = [
    # ELEKTRİK MOTORU
    {
        "name": "Motor Gücü",
        "slug": "elektrikli-motor-gucu",
        "group_slug": "elektrik-motoru",
        "data_type": "decimal",
        "unit": "kW",
        "display_order": 6000,
        "is_filterable": True,
        "is_comparable": True,
        "is_searchable": False,
    },
    {
        "name": "Motor Tipi",
        "slug": "elektrikli-motor-tipi",
        "group_slug": "elektrik-motoru",
        "data_type": "text",
        "unit": "",
        "display_order": 6010,
        "is_filterable": True,
        "is_comparable": True,
        "is_searchable": True,
    },
    {
        "name": "Sürüş Modları",
        "slug": "surus-modlari",
        "group_slug": "elektrik-motoru",
        "data_type": "text",
        "unit": "",
        "display_order": 6020,
        "is_filterable": False,
        "is_comparable": True,
        "is_searchable": False,
    },

    # BATARYA
    {
        "name": "Batarya Kapasitesi",
        "slug": "elektrikli-batarya-kapasitesi",
        "group_slug": "batarya",
        "data_type": "decimal",
        "unit": "kWh",
        "display_order": 6100,
        "is_filterable": True,
        "is_comparable": True,
        "is_searchable": False,
    },
    {
        "name": "Batarya Tipi",
        "slug": "elektrikli-batarya-tipi",
        "group_slug": "batarya",
        "data_type": "text",
        "unit": "",
        "display_order": 6110,
        "is_filterable": True,
        "is_comparable": True,
        "is_searchable": True,
    },
    {
        "name": "Batarya Garantisi",
        "slug": "elektrikli-batarya-garantisi",
        "group_slug": "batarya",
        "data_type": "integer",
        "unit": "Ay",
        "display_order": 6120,
        "is_filterable": False,
        "is_comparable": True,
        "is_searchable": False,
    },

    # ŞARJ
    {
        "name": "Şarj Süresi",
        "slug": "elektrikli-sarj-suresi",
        "group_slug": "sarj",
        "data_type": "decimal",
        "unit": "saat",
        "display_order": 6200,
        "is_filterable": False,
        "is_comparable": True,
        "is_searchable": False,
    },
    {
        "name": "Hızlı Şarj Desteği",
        "slug": "hizli-sarj-destegi",
        "group_slug": "sarj",
        "data_type": "boolean",
        "unit": "",
        "display_order": 6210,
        "is_filterable": True,
        "is_comparable": True,
        "is_searchable": False,
    },
    {
        "name": "Şarj Soketi Tipi",
        "slug": "sarj-soketi-tipi",
        "group_slug": "sarj",
        "data_type": "text",
        "unit": "",
        "display_order": 6220,
        "is_filterable": True,
        "is_comparable": True,
        "is_searchable": True,
    },

    # ELEKTRİKLİ PERFORMANS
    {
        "name": "Menzil",
        "slug": "elektrikli-menzil",
        "group_slug": "elektrikli-performans",
        "data_type": "integer",
        "unit": "km",
        "display_order": 6300,
        "is_filterable": True,
        "is_comparable": True,
        "is_searchable": False,
    },
    {
        "name": "Maksimum Hız",
        "slug": "elektrikli-maksimum-hiz",
        "group_slug": "elektrikli-performans",
        "data_type": "integer",
        "unit": "km/h",
        "display_order": 6310,
        "is_filterable": True,
        "is_comparable": True,
        "is_searchable": False,
    },
]