HELMET_ATTRIBUTE_DATA = [
    # GENEL BİLGİLER
    {
        "name": "Kask Tipi",
        "slug": "kask-tipi",
        "group_slug": "genel-bilgiler",
        "data_type": "text",
        "unit": "",
        "display_order": 1400,
        "is_filterable": True,
        "is_comparable": True,
        "is_searchable": True,
    },
    {
        "name": "Kullanım Türü",
        "slug": "kullanim-turu",
        "group_slug": "genel-bilgiler",
        "data_type": "text",
        "unit": "",
        "display_order": 1410,
        "is_filterable": True,
        "is_comparable": True,
        "is_searchable": True,
    },

    # MALZEME VE YAPI
    {
        "name": "Kabuk Malzemesi",
        "slug": "kabuk-malzemesi",
        "group_slug": "malzeme-ve-yapi",
        "data_type": "text",
        "unit": "",
        "display_order": 1500,
        "is_filterable": True,
        "is_comparable": True,
        "is_searchable": True,
    },
    {
        "name": "Kabuk Sayısı",
        "slug": "kabuk-sayisi",
        "group_slug": "malzeme-ve-yapi",
        "data_type": "integer",
        "unit": "",
        "display_order": 1510,
        "is_filterable": False,
        "is_comparable": True,
        "is_searchable": False,
    },
    {
        "name": "İç Darbe Emici Malzeme",
        "slug": "ic-darbe-emici-malzeme",
        "group_slug": "malzeme-ve-yapi",
        "data_type": "text",
        "unit": "",
        "display_order": 1520,
        "is_filterable": False,
        "is_comparable": True,
        "is_searchable": False,
    },
    {
        "name": "Ağırlık",
        "slug": "kask-agirligi",
        "group_slug": "malzeme-ve-yapi",
        "data_type": "integer",
        "unit": "g",
        "display_order": 1530,
        "is_filterable": True,
        "is_comparable": True,
        "is_searchable": False,
    },

    # VİZÖR VE GÖRÜŞ
    {
        "name": "Ana Vizör Tipi",
        "slug": "ana-vizor-tipi",
        "group_slug": "vizor-ve-gorus",
        "data_type": "text",
        "unit": "",
        "display_order": 1600,
        "is_filterable": True,
        "is_comparable": True,
        "is_searchable": False,
    },
    {
        "name": "Dahili Güneş Vizörü",
        "slug": "dahili-gunes-vizoru",
        "group_slug": "vizor-ve-gorus",
        "data_type": "boolean",
        "unit": "",
        "display_order": 1610,
        "is_filterable": True,
        "is_comparable": True,
        "is_searchable": False,
    },
    {
        "name": "Pinlock Uyumlu",
        "slug": "pinlock-uyumlu",
        "group_slug": "vizor-ve-gorus",
        "data_type": "boolean",
        "unit": "",
        "display_order": 1620,
        "is_filterable": True,
        "is_comparable": True,
        "is_searchable": False,
    },
    {
        "name": "Pinlock Dahil",
        "slug": "pinlock-dahil",
        "group_slug": "vizor-ve-gorus",
        "data_type": "boolean",
        "unit": "",
        "display_order": 1630,
        "is_filterable": True,
        "is_comparable": True,
        "is_searchable": False,
    },
    {
        "name": "Çizilmeye Dayanıklı Vizör",
        "slug": "cizilmeye-dayanikli-vizor",
        "group_slug": "vizor-ve-gorus",
        "data_type": "boolean",
        "unit": "",
        "display_order": 1640,
        "is_filterable": True,
        "is_comparable": True,
        "is_searchable": False,
    },
    {
        "name": "UV Koruması",
        "slug": "uv-korumasi",
        "group_slug": "vizor-ve-gorus",
        "data_type": "boolean",
        "unit": "",
        "display_order": 1650,
        "is_filterable": True,
        "is_comparable": True,
        "is_searchable": False,
    },

    # GÜVENLİK
    {
        "name": "Çene Bağlantı Tipi",
        "slug": "cene-baglanti-tipi",
        "group_slug": "guvenlik",
        "data_type": "text",
        "unit": "",
        "display_order": 1700,
        "is_filterable": True,
        "is_comparable": True,
        "is_searchable": False,
    },
    {
        "name": "Acil Durum Ped Çıkarma Sistemi",
        "slug": "acil-durum-ped-cikarma",
        "group_slug": "guvenlik",
        "data_type": "boolean",
        "unit": "",
        "display_order": 1710,
        "is_filterable": True,
        "is_comparable": True,
        "is_searchable": False,
    },
    {
        "name": "Reflektif Detay",
        "slug": "reflektif-detay",
        "group_slug": "guvenlik",
        "data_type": "boolean",
        "unit": "",
        "display_order": 1720,
        "is_filterable": True,
        "is_comparable": True,
        "is_searchable": False,
    },

    # KONFOR
    {
        "name": "İç Pedler Çıkarılabilir",
        "slug": "ic-pedler-cikarilabilir",
        "group_slug": "konfor",
        "data_type": "boolean",
        "unit": "",
        "display_order": 1800,
        "is_filterable": True,
        "is_comparable": True,
        "is_searchable": False,
    },
    {
        "name": "İç Pedler Yıkanabilir",
        "slug": "ic-pedler-yikanabilir",
        "group_slug": "konfor",
        "data_type": "boolean",
        "unit": "",
        "display_order": 1810,
        "is_filterable": True,
        "is_comparable": True,
        "is_searchable": False,
    },
    {
        "name": "Gözlük Kullanımına Uygun",
        "slug": "gozluk-kullanimina-uygun",
        "group_slug": "konfor",
        "data_type": "boolean",
        "unit": "",
        "display_order": 1820,
        "is_filterable": True,
        "is_comparable": True,
        "is_searchable": False,
    },
    {
        "name": "Intercom Hazırlığı",
        "slug": "intercom-hazirligi",
        "group_slug": "konfor",
        "data_type": "boolean",
        "unit": "",
        "display_order": 1830,
        "is_filterable": True,
        "is_comparable": True,
        "is_searchable": False,
    },
    {
        "name": "Burun Koruyucu",
        "slug": "burun-koruyucu",
        "group_slug": "konfor",
        "data_type": "boolean",
        "unit": "",
        "display_order": 1840,
        "is_filterable": False,
        "is_comparable": True,
        "is_searchable": False,
    },
    {
        "name": "Çene Perdesi",
        "slug": "cene-perdesi",
        "group_slug": "konfor",
        "data_type": "boolean",
        "unit": "",
        "display_order": 1850,
        "is_filterable": False,
        "is_comparable": True,
        "is_searchable": False,
    },

    # HAVALANDIRMA
    {
        "name": "Ön Hava Girişi Sayısı",
        "slug": "on-hava-girisi-sayisi",
        "group_slug": "havalandirma",
        "data_type": "integer",
        "unit": "",
        "display_order": 1900,
        "is_filterable": False,
        "is_comparable": True,
        "is_searchable": False,
    },
    {
        "name": "Arka Hava Çıkışı Sayısı",
        "slug": "arka-hava-cikisi-sayisi",
        "group_slug": "havalandirma",
        "data_type": "integer",
        "unit": "",
        "display_order": 1910,
        "is_filterable": False,
        "is_comparable": True,
        "is_searchable": False,
    },
    {
        "name": "Ayarlanabilir Havalandırma",
        "slug": "ayarlanabilir-havalandirma",
        "group_slug": "havalandirma",
        "data_type": "boolean",
        "unit": "",
        "display_order": 1920,
        "is_filterable": True,
        "is_comparable": True,
        "is_searchable": False,
    },

    # STANDARTLAR VE SERTİFİKALAR
    {
        "name": "ECE Sertifikası",
        "slug": "ece-sertifikasi",
        "group_slug": "standartlar-ve-sertifikalar",
        "data_type": "text",
        "unit": "",
        "display_order": 2000,
        "is_filterable": True,
        "is_comparable": True,
        "is_searchable": True,
    },
    {
        "name": "DOT Sertifikası",
        "slug": "dot-sertifikasi",
        "group_slug": "standartlar-ve-sertifikalar",
        "data_type": "boolean",
        "unit": "",
        "display_order": 2010,
        "is_filterable": True,
        "is_comparable": True,
        "is_searchable": False,
    },
    {
        "name": "SNELL Sertifikası",
        "slug": "snell-sertifikasi",
        "group_slug": "standartlar-ve-sertifikalar",
        "data_type": "boolean",
        "unit": "",
        "display_order": 2020,
        "is_filterable": True,
        "is_comparable": True,
        "is_searchable": False,
    },
    {
        "name": "P/J Homologasyonu",
        "slug": "pj-homologasyonu",
        "group_slug": "standartlar-ve-sertifikalar",
        "data_type": "boolean",
        "unit": "",
        "display_order": 2030,
        "is_filterable": True,
        "is_comparable": True,
        "is_searchable": False,
    },
]