MOTORCYCLE_ATTRIBUTE_DATA = [
    # MOTOR
    {
        "name": "Motor Hacmi",
        "slug": "motor-hacmi",
        "group_slug": "motor",
        "data_type": "integer",
        "unit": "cc",
        "display_order": 100,
        "is_filterable": True,
        "is_comparable": True,
        "is_searchable": True,
    },
    {
        "name": "Silindir Sayısı",
        "slug": "silindir-sayisi",
        "group_slug": "motor",
        "data_type": "integer",
        "unit": "",
        "display_order": 110,
        "is_filterable": True,
        "is_comparable": True,
        "is_searchable": False,
    },
    {
        "name": "Motor Tipi",
        "slug": "motor-tipi",
        "group_slug": "motor",
        "data_type": "text",
        "unit": "",
        "display_order": 120,
        "is_filterable": True,
        "is_comparable": True,
        "is_searchable": True,
    },
    {
        "name": "Soğutma Sistemi",
        "slug": "sogutma-sistemi",
        "group_slug": "motor",
        "data_type": "text",
        "unit": "",
        "display_order": 130,
        "is_filterable": True,
        "is_comparable": True,
        "is_searchable": False,
    },
    {
        "name": "Supap Sayısı",
        "slug": "supap-sayisi",
        "group_slug": "motor",
        "data_type": "integer",
        "unit": "",
        "display_order": 140,
        "is_filterable": False,
        "is_comparable": True,
        "is_searchable": False,
    },
    {
        "name": "Sıkıştırma Oranı",
        "slug": "sikistirma-orani",
        "group_slug": "motor",
        "data_type": "text",
        "unit": "",
        "display_order": 150,
        "is_filterable": False,
        "is_comparable": True,
        "is_searchable": False,
    },

    # PERFORMANS
    {
        "name": "Maksimum Güç",
        "slug": "maksimum-guc",
        "group_slug": "performans",
        "data_type": "decimal",
        "unit": "HP",
        "display_order": 200,
        "is_filterable": True,
        "is_comparable": True,
        "is_searchable": False,
    },
    {
        "name": "Maksimum Güç Devri",
        "slug": "maksimum-guc-devri",
        "group_slug": "performans",
        "data_type": "integer",
        "unit": "rpm",
        "display_order": 210,
        "is_filterable": False,
        "is_comparable": True,
        "is_searchable": False,
    },
    {
        "name": "Maksimum Tork",
        "slug": "maksimum-tork",
        "group_slug": "performans",
        "data_type": "decimal",
        "unit": "Nm",
        "display_order": 220,
        "is_filterable": True,
        "is_comparable": True,
        "is_searchable": False,
    },
    {
        "name": "Maksimum Tork Devri",
        "slug": "maksimum-tork-devri",
        "group_slug": "performans",
        "data_type": "integer",
        "unit": "rpm",
        "display_order": 230,
        "is_filterable": False,
        "is_comparable": True,
        "is_searchable": False,
    },
    {
        "name": "Maksimum Hız",
        "slug": "maksimum-hiz",
        "group_slug": "performans",
        "data_type": "integer",
        "unit": "km/h",
        "display_order": 240,
        "is_filterable": True,
        "is_comparable": True,
        "is_searchable": False,
    },

    # ŞANZIMAN VE AKTARMA
    {
        "name": "Şanzıman Tipi",
        "slug": "sanziman-tipi",
        "group_slug": "sanziman-ve-aktarma",
        "data_type": "text",
        "unit": "",
        "display_order": 300,
        "is_filterable": True,
        "is_comparable": True,
        "is_searchable": False,
    },
    {
        "name": "Vites Sayısı",
        "slug": "vites-sayisi",
        "group_slug": "sanziman-ve-aktarma",
        "data_type": "integer",
        "unit": "",
        "display_order": 310,
        "is_filterable": True,
        "is_comparable": True,
        "is_searchable": False,
    },
    {
        "name": "Debriyaj Tipi",
        "slug": "debriyaj-tipi",
        "group_slug": "sanziman-ve-aktarma",
        "data_type": "text",
        "unit": "",
        "display_order": 320,
        "is_filterable": True,
        "is_comparable": True,
        "is_searchable": False,
    },
    {
        "name": "Son Aktarma Tipi",
        "slug": "son-aktarma-tipi",
        "group_slug": "sanziman-ve-aktarma",
        "data_type": "text",
        "unit": "",
        "display_order": 330,
        "is_filterable": True,
        "is_comparable": True,
        "is_searchable": False,
    },

    # YAKIT VE ENERJİ
    {
        "name": "Yakıt Türü",
        "slug": "yakit-turu",
        "group_slug": "yakit-ve-enerji",
        "data_type": "text",
        "unit": "",
        "display_order": 400,
        "is_filterable": True,
        "is_comparable": True,
        "is_searchable": True,
    },
    {
        "name": "Yakıt Sistemi",
        "slug": "yakit-sistemi",
        "group_slug": "yakit-ve-enerji",
        "data_type": "text",
        "unit": "",
        "display_order": 410,
        "is_filterable": True,
        "is_comparable": True,
        "is_searchable": False,
    },
    {
        "name": "Yakıt Deposu",
        "slug": "yakit-deposu",
        "group_slug": "yakit-ve-enerji",
        "data_type": "decimal",
        "unit": "L",
        "display_order": 420,
        "is_filterable": True,
        "is_comparable": True,
        "is_searchable": False,
    },
    {
        "name": "Yakıt Tüketimi",
        "slug": "yakit-tuketimi",
        "group_slug": "yakit-ve-enerji",
        "data_type": "decimal",
        "unit": "L/100 km",
        "display_order": 430,
        "is_filterable": True,
        "is_comparable": True,
        "is_searchable": False,
    },

    # BOYUTLAR VE AĞIRLIK
    {
        "name": "Uzunluk",
        "slug": "uzunluk",
        "group_slug": "boyutlar-ve-agirlik",
        "data_type": "integer",
        "unit": "mm",
        "display_order": 500,
        "is_filterable": False,
        "is_comparable": True,
        "is_searchable": False,
    },
    {
        "name": "Genişlik",
        "slug": "genislik",
        "group_slug": "boyutlar-ve-agirlik",
        "data_type": "integer",
        "unit": "mm",
        "display_order": 510,
        "is_filterable": False,
        "is_comparable": True,
        "is_searchable": False,
    },
    {
        "name": "Yükseklik",
        "slug": "yukseklik",
        "group_slug": "boyutlar-ve-agirlik",
        "data_type": "integer",
        "unit": "mm",
        "display_order": 520,
        "is_filterable": False,
        "is_comparable": True,
        "is_searchable": False,
    },
    {
        "name": "Dingil Mesafesi",
        "slug": "dingil-mesafesi",
        "group_slug": "boyutlar-ve-agirlik",
        "data_type": "integer",
        "unit": "mm",
        "display_order": 530,
        "is_filterable": False,
        "is_comparable": True,
        "is_searchable": False,
    },
    {
        "name": "Sele Yüksekliği",
        "slug": "sele-yuksekligi",
        "group_slug": "boyutlar-ve-agirlik",
        "data_type": "integer",
        "unit": "mm",
        "display_order": 540,
        "is_filterable": True,
        "is_comparable": True,
        "is_searchable": False,
    },
    {
        "name": "Yerden Yükseklik",
        "slug": "yerden-yukseklik",
        "group_slug": "boyutlar-ve-agirlik",
        "data_type": "integer",
        "unit": "mm",
        "display_order": 550,
        "is_filterable": True,
        "is_comparable": True,
        "is_searchable": False,
    },
    {
        "name": "Boş Ağırlık",
        "slug": "bos-agirlik",
        "group_slug": "boyutlar-ve-agirlik",
        "data_type": "decimal",
        "unit": "kg",
        "display_order": 560,
        "is_filterable": True,
        "is_comparable": True,
        "is_searchable": False,
    },
    {
        "name": "Taşıma Kapasitesi",
        "slug": "tasima-kapasitesi",
        "group_slug": "boyutlar-ve-agirlik",
        "data_type": "decimal",
        "unit": "kg",
        "display_order": 570,
        "is_filterable": False,
        "is_comparable": True,
        "is_searchable": False,
    },

    # FREN SİSTEMİ
    {
        "name": "Ön Fren",
        "slug": "on-fren",
        "group_slug": "fren-sistemi",
        "data_type": "text",
        "unit": "",
        "display_order": 600,
        "is_filterable": False,
        "is_comparable": True,
        "is_searchable": False,
    },
    {
        "name": "Arka Fren",
        "slug": "arka-fren",
        "group_slug": "fren-sistemi",
        "data_type": "text",
        "unit": "",
        "display_order": 610,
        "is_filterable": False,
        "is_comparable": True,
        "is_searchable": False,
    },
    {
        "name": "ABS",
        "slug": "abs",
        "group_slug": "guvenlik",
        "data_type": "boolean",
        "unit": "",
        "display_order": 620,
        "is_filterable": True,
        "is_comparable": True,
        "is_searchable": False,
    },
    {
        "name": "CBS",
        "slug": "cbs",
        "group_slug": "guvenlik",
        "data_type": "boolean",
        "unit": "",
        "display_order": 630,
        "is_filterable": True,
        "is_comparable": True,
        "is_searchable": False,
    },

    # SÜSPANSİYON
    {
        "name": "Ön Süspansiyon",
        "slug": "on-suspansiyon",
        "group_slug": "suspansiyon",
        "data_type": "text",
        "unit": "",
        "display_order": 700,
        "is_filterable": False,
        "is_comparable": True,
        "is_searchable": False,
    },
    {
        "name": "Arka Süspansiyon",
        "slug": "arka-suspansiyon",
        "group_slug": "suspansiyon",
        "data_type": "text",
        "unit": "",
        "display_order": 710,
        "is_filterable": False,
        "is_comparable": True,
        "is_searchable": False,
    },

    # JANT VE LASTİK
    {
        "name": "Ön Lastik",
        "slug": "on-lastik",
        "group_slug": "jant-ve-lastik",
        "data_type": "text",
        "unit": "",
        "display_order": 800,
        "is_filterable": True,
        "is_comparable": True,
        "is_searchable": False,
    },
    {
        "name": "Arka Lastik",
        "slug": "arka-lastik",
        "group_slug": "jant-ve-lastik",
        "data_type": "text",
        "unit": "",
        "display_order": 810,
        "is_filterable": True,
        "is_comparable": True,
        "is_searchable": False,
    },
    {
        "name": "Ön Jant",
        "slug": "on-jant",
        "group_slug": "jant-ve-lastik",
        "data_type": "text",
        "unit": "",
        "display_order": 820,
        "is_filterable": False,
        "is_comparable": True,
        "is_searchable": False,
    },
    {
        "name": "Arka Jant",
        "slug": "arka-jant",
        "group_slug": "jant-ve-lastik",
        "data_type": "text",
        "unit": "",
        "display_order": 830,
        "is_filterable": False,
        "is_comparable": True,
        "is_searchable": False,
    },

    # ELEKTRİK VE ELEKTRONİK
    {
        "name": "Akü",
        "slug": "aku",
        "group_slug": "elektrik-ve-elektronik",
        "data_type": "text",
        "unit": "",
        "display_order": 900,
        "is_filterable": False,
        "is_comparable": True,
        "is_searchable": False,
    },
    {
        "name": "Far Tipi",
        "slug": "far-tipi",
        "group_slug": "elektrik-ve-elektronik",
        "data_type": "text",
        "unit": "",
        "display_order": 910,
        "is_filterable": True,
        "is_comparable": True,
        "is_searchable": False,
    },
    {
        "name": "Gösterge Paneli",
        "slug": "gosterge-paneli",
        "group_slug": "elektrik-ve-elektronik",
        "data_type": "text",
        "unit": "",
        "display_order": 920,
        "is_filterable": True,
        "is_comparable": True,
        "is_searchable": False,
    },

    # GÜVENLİK
    {
        "name": "Çekiş Kontrolü",
        "slug": "cekis-kontrolu",
        "group_slug": "guvenlik",
        "data_type": "boolean",
        "unit": "",
        "display_order": 1000,
        "is_filterable": True,
        "is_comparable": True,
        "is_searchable": False,
    },
    {
        "name": "İmmobilizer",
        "slug": "immobilizer",
        "group_slug": "guvenlik",
        "data_type": "boolean",
        "unit": "",
        "display_order": 1010,
        "is_filterable": True,
        "is_comparable": True,
        "is_searchable": False,
    },

    # DONANIM
    {
        "name": "USB Şarj Girişi",
        "slug": "usb-sarj-girisi",
        "group_slug": "donanim",
        "data_type": "boolean",
        "unit": "",
        "display_order": 1100,
        "is_filterable": True,
        "is_comparable": True,
        "is_searchable": False,
    },
    {
        "name": "Anahtarsız Çalıştırma",
        "slug": "anahtarsiz-calistirma",
        "group_slug": "donanim",
        "data_type": "boolean",
        "unit": "",
        "display_order": 1110,
        "is_filterable": True,
        "is_comparable": True,
        "is_searchable": False,
    },
]