OIL_ATTRIBUTE_DATA = [
    # GENEL BİLGİLER
    {
        "name": "Yağ Türü",
        "slug": "yag-turu",
        "group_slug": "genel-bilgiler",
        "data_type": "text",
        "unit": "",
        "display_order": 4200,
        "is_filterable": True,
        "is_comparable": True,
        "is_searchable": True,
    },
    {
        "name": "Motor Tipi",
        "slug": "yag-motor-tipi",
        "group_slug": "genel-bilgiler",
        "data_type": "text",
        "unit": "",
        "display_order": 4210,
        "is_filterable": True,
        "is_comparable": True,
        "is_searchable": True,
    },

    # YAĞ TEKNİK DEĞERLERİ
    {
        "name": "Viskozite",
        "slug": "viskozite",
        "group_slug": "yag-teknik-degerleri",
        "data_type": "text",
        "unit": "",
        "display_order": 4300,
        "is_filterable": True,
        "is_comparable": True,
        "is_searchable": True,
    },
    {
        "name": "Baz Yağ Tipi",
        "slug": "baz-yag-tipi",
        "group_slug": "yag-teknik-degerleri",
        "data_type": "text",
        "unit": "",
        "display_order": 4310,
        "is_filterable": True,
        "is_comparable": True,
        "is_searchable": False,
    },
    {
        "name": "Hacim",
        "slug": "yag-hacmi",
        "group_slug": "yag-teknik-degerleri",
        "data_type": "decimal",
        "unit": "L",
        "display_order": 4320,
        "is_filterable": True,
        "is_comparable": True,
        "is_searchable": False,
    },

    # YAĞ STANDARTLARI
    {
        "name": "API Standardı",
        "slug": "api-standardi",
        "group_slug": "yag-standartlari",
        "data_type": "text",
        "unit": "",
        "display_order": 4400,
        "is_filterable": True,
        "is_comparable": True,
        "is_searchable": True,
    },
    {
        "name": "JASO Standardı",
        "slug": "jaso-standardi",
        "group_slug": "yag-standartlari",
        "data_type": "text",
        "unit": "",
        "display_order": 4410,
        "is_filterable": True,
        "is_comparable": True,
        "is_searchable": True,
    },
    {
        "name": "ACEA Standardı",
        "slug": "acea-standardi",
        "group_slug": "yag-standartlari",
        "data_type": "text",
        "unit": "",
        "display_order": 4420,
        "is_filterable": True,
        "is_comparable": True,
        "is_searchable": True,
    },

    # KULLANIM ALANI
    {
        "name": "Kullanım Alanı",
        "slug": "yag-kullanim-alani",
        "group_slug": "kullanim-alani",
        "data_type": "text",
        "unit": "",
        "display_order": 4500,
        "is_filterable": True,
        "is_comparable": True,
        "is_searchable": True,
    },
    {
        "name": "Islak Debriyaj Uyumlu",
        "slug": "islak-debriyaj-uyumlu",
        "group_slug": "kullanim-alani",
        "data_type": "boolean",
        "unit": "",
        "display_order": 4510,
        "is_filterable": True,
        "is_comparable": True,
        "is_searchable": False,
    },
    {
        "name": "2T / 4T",
        "slug": "iki-zamanli-dort-zamanli",
        "group_slug": "kullanim-alani",
        "data_type": "text",
        "unit": "",
        "display_order": 4520,
        "is_filterable": True,
        "is_comparable": True,
        "is_searchable": True,
    },

    # UYUMLULUK
    {
        "name": "Uyumlu Motosiklet",
        "slug": "yag-uyumlu-motosiklet",
        "group_slug": "uyumluluk",
        "data_type": "text",
        "unit": "",
        "display_order": 4600,
        "is_filterable": True,
        "is_comparable": False,
        "is_searchable": True,
    },

    # STANDARTLAR
    {
        "name": "Üretici Onayı",
        "slug": "uretici-onayi",
        "group_slug": "standartlar-ve-sertifikalar",
        "data_type": "text",
        "unit": "",
        "display_order": 4700,
        "is_filterable": True,
        "is_comparable": True,
        "is_searchable": True,
    },
]