PARTS_ATTRIBUTE_DATA = [
    # PARÇA BİLGİLERİ
    {
        "name": "Parça Tipi",
        "slug": "parca-tipi",
        "group_slug": "parca-bilgileri",
        "data_type": "text",
        "unit": "",
        "display_order": 7000,
        "is_filterable": True,
        "is_comparable": True,
        "is_searchable": True,
    },
    {
        "name": "Renk",
        "slug": "parca-rengi",
        "group_slug": "parca-bilgileri",
        "data_type": "text",
        "unit": "",
        "display_order": 7010,
        "is_filterable": True,
        "is_comparable": False,
        "is_searchable": False,
    },
    {
        "name": "Zincir Ölçüsü",
        "slug": "zincir-olcusu",
        "group_slug": "parca-bilgileri",
        "data_type": "text",
        "unit": "",
        "display_order": 7020,
        "is_filterable": True,
        "is_comparable": True,
        "is_searchable": True,
    },
    {
        "name": "Diş Sayısı",
        "slug": "dis-sayisi",
        "group_slug": "parca-bilgileri",
        "data_type": "integer",
        "unit": "",
        "display_order": 7030,
        "is_filterable": True,
        "is_comparable": True,
        "is_searchable": False,
    },
    {
        "name": "Filtre Tipi",
        "slug": "filtre-tipi",
        "group_slug": "parca-bilgileri",
        "data_type": "text",
        "unit": "",
        "display_order": 7040,
        "is_filterable": True,
        "is_comparable": True,
        "is_searchable": False,
    },
    {
        "name": "Kasa Koruma Tipi",
        "slug": "kasa-koruma-tipi",
        "group_slug": "parca-bilgileri",
        "data_type": "text",
        "unit": "",
        "display_order": 7050,
        "is_filterable": True,
        "is_comparable": True,
        "is_searchable": False,
    },

    # PARÇA MALZEME VE YAPI
    {
        "name": "Malzeme",
        "slug": "parca-malzemesi",
        "group_slug": "parca-malzeme-ve-yapi",
        "data_type": "text",
        "unit": "",
        "display_order": 7100,
        "is_filterable": True,
        "is_comparable": True,
        "is_searchable": True,
    },
    {
        "name": "Ağırlık",
        "slug": "parca-agirligi",
        "group_slug": "parca-malzeme-ve-yapi",
        "data_type": "decimal",
        "unit": "kg",
        "display_order": 7110,
        "is_filterable": False,
        "is_comparable": True,
        "is_searchable": False,
    },

    # BUJİ ÖZELLİKLERİ
    {
        "name": "Elektrot Aralığı",
        "slug": "elektrot-araligi",
        "group_slug": "parca-bilgileri",
        "data_type": "decimal",
        "unit": "mm",
        "display_order": 7200,
        "is_filterable": True,
        "is_comparable": True,
        "is_searchable": False,
    },
    {
        "name": "Termal Değer",
        "slug": "termal-deger",
        "group_slug": "parca-bilgileri",
        "data_type": "text",
        "unit": "",
        "display_order": 7210,
        "is_filterable": True,
        "is_comparable": True,
        "is_searchable": True,
    },
    {
        "name": "Diş Çapı",
        "slug": "dis-capi",
        "group_slug": "parca-bilgileri",
        "data_type": "text",
        "unit": "",
        "display_order": 7220,
        "is_filterable": True,
        "is_comparable": True,
        "is_searchable": False,
    },
    {
        "name": "Diş Uzunluğu",
        "slug": "dis-uzunlugu",
        "group_slug": "parca-bilgileri",
        "data_type": "decimal",
        "unit": "mm",
        "display_order": 7230,
        "is_filterable": False,
        "is_comparable": True,
        "is_searchable": False,
    },
    {
        "name": "Anahtar Ağzı",
        "slug": "anahtar-agzi",
        "group_slug": "parca-bilgileri",
        "data_type": "text",
        "unit": "mm",
        "display_order": 7240,
        "is_filterable": False,
        "is_comparable": True,
        "is_searchable": False,
    },

     # LASTİK ÖZELLİKLERİ
    {
        "name": "Lastik Malzemesi",
        "slug": "lastik-malzemesi",
        "group_slug": "parca-malzeme-ve-yapi",
        "data_type": "single_select",
        "unit": "",
        "display_order": 7300,
        "is_filterable": True,
        "is_comparable": True,
        "is_searchable": False,
    },
    {
        "name": "Lastik Tipi",
        "slug": "lastik-tipi",
        "group_slug": "parca-bilgileri",
        "data_type": "single_select",
        "unit": "",
        "display_order": 7310,
        "is_filterable": True,
        "is_comparable": True,
        "is_searchable": True,
    },
    
]
