PROTECTION_ATTRIBUTE_DATA = [
    {
        "name": "Koruma Standardı",
        "slug": "koruma-standardi",
        "group_slug": "koruma-ve-guvenlik",
        "data_type": "single_select",
        "unit": "",
        "display_order": 3800,
        "is_filterable": True,
        "is_comparable": True,
        "is_searchable": False,
    },
    {
        "name": "Koruma Seviyesi",
        "slug": "koruma-seviyesi",
        "group_slug": "koruma-ve-guvenlik",
        "data_type": "single_select",
        "unit": "",
        "display_order": 3810,
        "is_filterable": True,
        "is_comparable": True,
        "is_searchable": False,
    },
    {
        "name": "Koruyucu Malzemesi",
        "slug": "koruyucu-malzemesi",
        "group_slug": "malzeme-ve-yapi",
        "data_type": "single_select",
        "unit": "",
        "display_order": 3820,
        "is_filterable": True,
        "is_comparable": True,
        "is_searchable": False,
    },
    {
        "name": "Kullanım Şekli",
        "slug": "kullanim-sekli",
        "group_slug": "koruma-ve-guvenlik",
        "data_type": "single_select",
        "unit": "",
        "display_order": 3830,
        "is_filterable": True,
        "is_comparable": True,
        "is_searchable": False,
    },
    {
        "name": "Havalandırmalı",
        "slug": "havalandirmali",
        "group_slug": "kullanim-ve-konfor",
        "data_type": "boolean",
        "unit": "",
        "display_order": 3840,
        "is_filterable": True,
        "is_comparable": True,
        "is_searchable": False,
    },
]
