SCOOTER_ATTRIBUTE_DATA = [
    {
        "name": "Sele Altı Bagaj Hacmi",
        "slug": "sele-alti-bagaj-hacmi",
        "group_slug": "boyutlar-ve-agirlik",
        "data_type": "decimal",
        "unit": "L",
        "display_order": 1200,
        "is_filterable": True,
        "is_comparable": True,
        "is_searchable": False,
    },
    {
        "name": "Düz Taban",
        "slug": "duz-taban",
        "group_slug": "donanim",
        "data_type": "boolean",
        "unit": "",
        "display_order": 1210,
        "is_filterable": True,
        "is_comparable": True,
        "is_searchable": False,
    },
    {
        "name": "Ön Cam",
        "slug": "on-cam",
        "group_slug": "donanim",
        "data_type": "boolean",
        "unit": "",
        "display_order": 1220,
        "is_filterable": True,
        "is_comparable": True,
        "is_searchable": False,
    },
    {
        "name": "Start-Stop Sistemi",
        "slug": "start-stop-sistemi",
        "group_slug": "donanim",
        "data_type": "boolean",
        "unit": "",
        "display_order": 1230,
        "is_filterable": True,
        "is_comparable": True,
        "is_searchable": False,
    },
    {
        "name": "Idling Stop",
        "slug": "idling-stop",
        "group_slug": "donanim",
        "data_type": "boolean",
        "unit": "",
        "display_order": 1240,
        "is_filterable": True,
        "is_comparable": True,
        "is_searchable": False,
    },
    {
        "name": "Akıllı Anahtar",
        "slug": "akilli-anahtar",
        "group_slug": "donanim",
        "data_type": "boolean",
        "unit": "",
        "display_order": 1250,
        "is_filterable": True,
        "is_comparable": True,
        "is_searchable": False,
    },
    {
        "name": "Telefon Bağlantısı",
        "slug": "telefon-baglantisi",
        "group_slug": "elektrik-ve-elektronik",
        "data_type": "boolean",
        "unit": "",
        "display_order": 1260,
        "is_filterable": True,
        "is_comparable": True,
        "is_searchable": False,
    },
    {
        "name": "Navigasyon Desteği",
        "slug": "navigasyon-destegi",
        "group_slug": "elektrik-ve-elektronik",
        "data_type": "boolean",
        "unit": "",
        "display_order": 1270,
        "is_filterable": True,
        "is_comparable": True,
        "is_searchable": False,
    },
    {
        "name": "Arka Portbagaj",
        "slug": "arka-portbagaj",
        "group_slug": "donanim",
        "data_type": "boolean",
        "unit": "",
        "display_order": 1280,
        "is_filterable": True,
        "is_comparable": True,
        "is_searchable": False,
    },
    {
        "name": "Ayak Marşı",
        "slug": "ayak-marsi",
        "group_slug": "donanim",
        "data_type": "boolean",
        "unit": "",
        "display_order": 1290,
        "is_filterable": True,
        "is_comparable": True,
        "is_searchable": False,
    },
    {
        "name": "El Freni",
        "slug": "el-freni",
        "group_slug": "fren-sistemi",
        "data_type": "boolean",
        "unit": "",
        "display_order": 1300,
        "is_filterable": True,
        "is_comparable": True,
        "is_searchable": False,
    },
    {
        "name": "Ön Saklama Gözü",
        "slug": "on-saklama-gozu",
        "group_slug": "donanim",
        "data_type": "boolean",
        "unit": "",
        "display_order": 1310,
        "is_filterable": True,
        "is_comparable": True,
        "is_searchable": False,
    },
    {
        "name": "Yakıt Deposu Konumu",
        "slug": "yakit-deposu-konumu",
        "group_slug": "yakit-ve-enerji",
        "data_type": "text",
        "unit": "",
        "display_order": 1320,
        "is_filterable": False,
        "is_comparable": True,
        "is_searchable": False,
    },
]