TIRE_ATTRIBUTE_DATA = [
    # GENEL BİLGİLER
    {
        "name": "Lastik Türü",
        "slug": "lastik-turu",
        "group_slug": "genel-bilgiler",
        "data_type": "text",
        "unit": "",
        "display_order": 2900,
        "is_filterable": True,
        "is_comparable": True,
        "is_searchable": True,
    },
    {
        "name": "Kullanım Konumu",
        "slug": "kullanim-konumu",
        "group_slug": "genel-bilgiler",
        "data_type": "text",
        "unit": "",
        "display_order": 2910,
        "is_filterable": True,
        "is_comparable": True,
        "is_searchable": True,
    },
    {
        "name": "İç Lastikli / Tubeless",
        "slug": "ic-lastikli-tubeless",
        "group_slug": "genel-bilgiler",
        "data_type": "text",
        "unit": "",
        "display_order": 2920,
        "is_filterable": True,
        "is_comparable": True,
        "is_searchable": True,
    },

    # LASTİK ÖLÇÜLERİ
    {
        "name": "Taban Genişliği",
        "slug": "taban-genisligi",
        "group_slug": "lastik-olculeri",
        "data_type": "integer",
        "unit": "mm",
        "display_order": 3000,
        "is_filterable": True,
        "is_comparable": True,
        "is_searchable": True,
    },
    {
        "name": "Kesit Oranı",
        "slug": "kesit-orani",
        "group_slug": "lastik-olculeri",
        "data_type": "integer",
        "unit": "%",
        "display_order": 3010,
        "is_filterable": True,
        "is_comparable": True,
        "is_searchable": True,
    },
    {
        "name": "Jant Çapı",
        "slug": "jant-capi",
        "group_slug": "lastik-olculeri",
        "data_type": "integer",
        "unit": "inç",
        "display_order": 3020,
        "is_filterable": True,
        "is_comparable": True,
        "is_searchable": True,
    },
    {
        "name": "Lastik Ebatı",
        "slug": "lastik-ebati",
        "group_slug": "lastik-olculeri",
        "data_type": "text",
        "unit": "",
        "display_order": 3030,
        "is_filterable": True,
        "is_comparable": True,
        "is_searchable": True,
    },

    # LASTİK YAPISI
    {
        "name": "Yapı Tipi",
        "slug": "yapi-tipi",
        "group_slug": "lastik-yapisi",
        "data_type": "text",
        "unit": "",
        "display_order": 3100,
        "is_filterable": True,
        "is_comparable": True,
        "is_searchable": True,
    },
    {
        "name": "Kat Yapısı",
        "slug": "kat-yapisi",
        "group_slug": "lastik-yapisi",
        "data_type": "text",
        "unit": "",
        "display_order": 3110,
        "is_filterable": False,
        "is_comparable": True,
        "is_searchable": False,
    },
    {
        "name": "Karkas Tipi",
        "slug": "karkas-tipi",
        "group_slug": "lastik-yapisi",
        "data_type": "text",
        "unit": "",
        "display_order": 3120,
        "is_filterable": True,
        "is_comparable": True,
        "is_searchable": False,
    },
    {
        "name": "Hamur Tipi",
        "slug": "hamur-tipi",
        "group_slug": "lastik-yapisi",
        "data_type": "text",
        "unit": "",
        "display_order": 3130,
        "is_filterable": True,
        "is_comparable": True,
        "is_searchable": False,
    },
    {
        "name": "Desen Tipi",
        "slug": "desen-tipi",
        "group_slug": "lastik-yapisi",
        "data_type": "text",
        "unit": "",
        "display_order": 3140,
        "is_filterable": True,
        "is_comparable": True,
        "is_searchable": True,
    },

    # PERFORMANS ENDEKSLERİ
    {
        "name": "Yük Endeksi",
        "slug": "yuk-endeksi",
        "group_slug": "performans-endeksleri",
        "data_type": "text",
        "unit": "",
        "display_order": 3200,
        "is_filterable": True,
        "is_comparable": True,
        "is_searchable": True,
    },
    {
        "name": "Hız Endeksi",
        "slug": "hiz-endeksi",
        "group_slug": "performans-endeksleri",
        "data_type": "text",
        "unit": "",
        "display_order": 3210,
        "is_filterable": True,
        "is_comparable": True,
        "is_searchable": True,
    },
    {
        "name": "Maksimum Yük",
        "slug": "maksimum-yuk",
        "group_slug": "performans-endeksleri",
        "data_type": "integer",
        "unit": "kg",
        "display_order": 3220,
        "is_filterable": False,
        "is_comparable": True,
        "is_searchable": False,
    },
    {
        "name": "Maksimum Hız",
        "slug": "lastik-maksimum-hiz",
        "group_slug": "performans-endeksleri",
        "data_type": "integer",
        "unit": "km/h",
        "display_order": 3230,
        "is_filterable": False,
        "is_comparable": True,
        "is_searchable": False,
    },
    {
        "name": "Islak Zemin Performansı",
        "slug": "islak-zemin-performansi",
        "group_slug": "performans-endeksleri",
        "data_type": "text",
        "unit": "",
        "display_order": 3240,
        "is_filterable": True,
        "is_comparable": True,
        "is_searchable": False,
    },

    # KULLANIM VE YOL TİPİ
    {
        "name": "Kullanım Alanı",
        "slug": "lastik-kullanim-alani",
        "group_slug": "kullanim-ve-yol-tipi",
        "data_type": "text",
        "unit": "",
        "display_order": 3300,
        "is_filterable": True,
        "is_comparable": True,
        "is_searchable": True,
    },
    {
        "name": "Yol / Arazi Oranı",
        "slug": "yol-arazi-orani",
        "group_slug": "kullanim-ve-yol-tipi",
        "data_type": "text",
        "unit": "",
        "display_order": 3310,
        "is_filterable": True,
        "is_comparable": True,
        "is_searchable": False,
    },
    {
        "name": "Mevsim Kullanımı",
        "slug": "lastik-mevsim-kullanimi",
        "group_slug": "kullanim-ve-yol-tipi",
        "data_type": "text",
        "unit": "",
        "display_order": 3320,
        "is_filterable": True,
        "is_comparable": True,
        "is_searchable": True,
    },
    {
        "name": "Yağmur Performansı",
        "slug": "yagmur-performansi",
        "group_slug": "kullanim-ve-yol-tipi",
        "data_type": "text",
        "unit": "",
        "display_order": 3330,
        "is_filterable": True,
        "is_comparable": True,
        "is_searchable": False,
    },

    # UYUMLULUK
    {
        "name": "Uyumlu Motosiklet Tipi",
        "slug": "uyumlu-motosiklet-tipi",
        "group_slug": "uyumluluk",
        "data_type": "text",
        "unit": "",
        "display_order": 3400,
        "is_filterable": True,
        "is_comparable": False,
        "is_searchable": True,
    },

    # STANDARTLAR VE SERTİFİKALAR
    {
        "name": "ECE Onayı",
        "slug": "lastik-ece-onayi",
        "group_slug": "standartlar-ve-sertifikalar",
        "data_type": "boolean",
        "unit": "",
        "display_order": 3500,
        "is_filterable": True,
        "is_comparable": True,
        "is_searchable": False,
    },
    {
        "name": "DOT Kodu",
        "slug": "dot-kodu",
        "group_slug": "standartlar-ve-sertifikalar",
        "data_type": "text",
        "unit": "",
        "display_order": 3510,
        "is_filterable": False,
        "is_comparable": False,
        "is_searchable": True,
    },
]