from .apparel import APPAREL_ATTRIBUTE_GROUP_DATA
from .accessories import ACCESSORIES_ATTRIBUTE_GROUP_DATA
from .battery import BATTERY_ATTRIBUTE_GROUP_DATA
from .bicycle import BICYCLE_ATTRIBUTE_GROUP_DATA
from .ecommerce import ECOMMERCE_ATTRIBUTE_GROUP_DATA
from .electric import ELECTRIC_ATTRIBUTE_GROUP_DATA
from .helmet import HELMET_ATTRIBUTE_GROUP_DATA
from .motorcycle import MOTORCYCLE_ATTRIBUTE_GROUP_DATA
from .oil import OIL_ATTRIBUTE_GROUP_DATA
from .parts import PARTS_ATTRIBUTE_GROUP_DATA
from .scooter import SCOOTER_ATTRIBUTE_GROUP_DATA
from .tire import TIRE_ATTRIBUTE_GROUP_DATA


ATTRIBUTE_GROUP_DATA = [
    *ECOMMERCE_ATTRIBUTE_GROUP_DATA,
    *MOTORCYCLE_ATTRIBUTE_GROUP_DATA,
    *SCOOTER_ATTRIBUTE_GROUP_DATA,
    *HELMET_ATTRIBUTE_GROUP_DATA,
    *APPAREL_ATTRIBUTE_GROUP_DATA,
    *TIRE_ATTRIBUTE_GROUP_DATA,
    *BATTERY_ATTRIBUTE_GROUP_DATA,
    *OIL_ATTRIBUTE_GROUP_DATA,
    *BICYCLE_ATTRIBUTE_GROUP_DATA,
    *ELECTRIC_ATTRIBUTE_GROUP_DATA,
    *PARTS_ATTRIBUTE_GROUP_DATA,
    *ACCESSORIES_ATTRIBUTE_GROUP_DATA,
]